### ISSUE TITLE
Spring intergration not support send message with timeout 

### ISSUE THREAD

**Issue by nzb15555196162** [spring-projects/spring-integration#3841] opened 2022-07-11 00:35 UTC
**In what version(s) of Spring Integration are you seeing this issue?**

5.3.2.RELEASE

**Describe the bug**
i use mq send timeout message with Spring intergration module, but it not working. 

**To Reproduce**
1 send message with spring messaging
2 set timeout parameter
  
**Expected behavior**
timeout parameter should work.

please see snapshot
![图片](https://user-images.githubusercontent.com/18350673/178168783-90f1ba35-8d72-4255-87ce-769b7344097e.gif)

**Comment by artembilan** [comment] 2022-07-11 01:58
Would you mind to share with us, please, how you send a message and where you’d like to have a timeout in effect ? The code you are pointing has nothing to do with timeouts: a sent message is performed without blocking.

**Comment by nzb15555196162** [comment] 2022-07-11 05:11
> 

first i sent message with rocketmq base on Spring Cloud Stream
the reason which i want to timeout is rocketmq sent message frequent timeouts so i set time out sent message,
but unfortunately it does not work with timeout, when i debug i found Spring intergration module not support send message with timeout.

**Comment by artembilan** [comment] 2022-07-11 13:54
@nzb15555196162 ,

sorry, this is still not clear what is going on.
I only can say that it works as expected since a `DirectChannel` propagates a message to the handler via that dispatcher immediately. There is just nothing to wait for. No blocking async barrier which would lead to idle period.
See `QueueChannel` docs when that `sendTimeout` makes sense: https://docs.spring.io/spring-integration/docs/current/reference/html/core.html#channel-implementations-queuechannel.
But this one is not used in Spring Cloud Stream bindings.
So, to help you more we need to know more about the place where you go a timeout.
Probably that is already out of this project scope and might be revised from the mentioned RocketMQ perspective.

I'm closing this one as `Works as Designed`.
Please, consider to start next time from StackOveflow with much more info.

**Comment by nzb15555196162** [comment] 2022-07-13 04:22
> @artembilan 
thank you for your reply, i will check

**Closed** 2022-07-13 13:36 UTC
Labels: status: invalid
