### ISSUE TITLE
RedisLock/JdbcLock doesn't acquire lock after expiry on different thread

### ISSUE THREAD

**Issue by gigermocas** [spring-projects/spring-integration#3821] opened 2022-06-07 11:31 UTC
Hello, 

I'm currently implementing in a project a distributed locking mechanism using redis and spring-integration.

The behavior I'm seeing is that using a single `RedisLockRegistry` in a multithreaded application, when locks are released in a thread due to lock  expiry another thread isn't able to acquire the lock and proceed.
This works fine if the first lock was obtained in a different instance (jvm).

I was expecting that the behavior would be exactly the same, as a "client" is effectively a thread that is doing a unit of work.

I'm assuming that a lock registry is supposed to be shared between threads, seems natural to me, and I didn't find anything in the documentation that warns against it.

From what I could see, the issue lies with the usage of a `ReentrantLock` before trying the repository, as it's the same for a `RedisLock` instance, so all threads will effectively lock on it first.
The zookeeper implementation, for example, always lock through the repository if locking is tried for the same `ZkLock` instance in a different thread (per its use of a per thread lock data instance). Maybe something similar would make sense for the other implementations?

I've added a test to reproduce this, including one for the jdbc implementation, as it has the same behavior, please see https://github.com/gigermocas/spring-integration/commit/9a96703afb061077b6879fb412297dc38ae06750

Tested in latest 5.5.x.

**Comment by artembilan** [comment] 2022-06-07 14:17
The behavior is correct and fully expected with a `ReentrantLock` algorithm.

You should ensure that expire duration is bigger than your one thread would hold the lock.
Technically we don't need TTL at all, but there is no way to clean it up from the store safely in case of application crash.
So, it is not OK to rely on the expire action for your business logic. Just because in distributed system it would be possible to have to processes to hold the same lock: one holding now just has no knowledge that its lock has been expired in the store and other process has been able to lock in its environment.
Also, even if an expire action happens we cannot do anything with your process which holds that  `ReentrantLock` currently.

It is even better to say that `ZkLock` is wrong without a local `ReentrantLock` , but there is just no any `timeToLive` option to weaken the system on the other side.

**Comment by gigermocas** [comment] 2022-06-07 15:39
This came about during edge case testing, this is not something I'm expecting to see.
From my perspective, spinning a new instance of my service or adding a new consumer thread should be able to handle this feature consistently in the same manner. This was somewhat surprising to me, and I didn't see it was obvious from looking at the documentation.

Thank you for your time, feel free to close this.

**Comment by artembilan** [comment] 2022-06-07 15:43
Thanks for confirmation!

Closed as `Works as Designed`

**Closed by artembilan** 2022-06-07 15:43 UTC
Labels: status: waiting-for-reporter
