### ISSUE TITLE
Default Message History in XML configuration throws an exception

### ISSUE THREAD

**Issue by pangyikhei** [spring-projects/spring-integration#3703] opened 2021-12-28 21:10 UTC
**In what version(s) of Spring Integration are you seeing this issue?**

5.5.6 and 5.5.7

**Describe the bug**

One of my integration xml files has a `<int:message-history/>` element which fails with an exception when calling GenericApplicationContext.refresh() after the upgrade to Spring Integration 5.5.6. 5.5.5 works fine.

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messageHistoryConfigurer': Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'componentNamePatterns' threw exception; nested exception is java.lang.IllegalArgumentException: componentNamePatterns must not be empty

If I specify tracked-components explicitly with the default value, the exception is not thrown.

Ex.

`<int:message-history tracked-components="*"/>`

**To Reproduce**

Integration configuration XML containing `<int:message-history/>`

````
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:int="http://www.springframework.org/schema/integration"
  xsi:schemaLocation="http://www.springframework.org/schema/integration http://www.springframework.org/schema/integration/spring-integration.xsd
		http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

   ...

   <int:message-history/>

   ...

</beans>
````

````
GenericApplicationContext context = new GenericApplicationContext();
XmlBeanDefinitionReader xmlReader = new XmlBeanDefinitionReader(context);
xmlReader.setValidationMode(XmlBeanDefinitionReader.VALIDATION_NONE);
xmlReader.setNamespaceAware(true);
xmlReader.loadBeanDefinitions("classpath:META-INF/project/spring/config.xml");
context.refresh();
````

**Expected behavior**

The default element should not throw an error and should use the default of `*`.

**Comment by artembilan** [comment] 2022-01-03 15:02
I'm confused.

We have a lot of tests in the project when we just have a `<int:message-history/>` without any attributes.
More over its XSD is like this:
```
<xsd:attribute name="tracked-components" type="xsd:string" default="*">
```
So, there is indeed that default for `*`.
I wonder why would one do that `XmlBeanDefinitionReader` manually, but not use `ClassPathXmlApplicationContext` instead?..

**Comment by artembilan** [comment] 2022-01-03 15:09
Well, I have reproduced exactly with your code, but when I comment  out this:
```
xmlReader.setValidationMode(XmlBeanDefinitionReader.VALIDATION_NONE);
```
It starts working.

Looking deeper...

**Comment by pangyikhei** [comment] 2022-01-03 15:26
> 

This code was used in our legacy codebase which I'm not too familiar with (the original devs are not with us anymore) in a test class. The snippet has been untouched since at least Spring 4 or earlier.

**Comment by artembilan** [comment] 2022-01-03 15:52
I'm not sure how that `XmlBeanDefinitionReader.VALIDATION_NONE` effect the output, but it comes with the `private int validationMode = VALIDATION_AUTO;` by default.
It is really expected to have some breaking changes after migrating from Spring 4 to Spring 5.
So, consider to fix your unit test respective and let's move on. 
I don't think it is going to be easy to find the reason behind and so on...

**Comment by artembilan** [comment] 2022-01-03 16:09
Looks like without validation the `XmlBeanDefinitionReader` (or its `DocumentBuilderFactory`) doesn't load an XSD to pull a default values for XML attributes.

I would say it is wrong to use an internal API (`XmlBeanDefinitionReader`) in the end-project unit tests. 
Better to rely on the high-level one like `ClassPathXmlApplicationContext`. Because this is exactly what is going to be used in the production.
You must not test the framework code in your project: only do unit (and integration) tests for your own code.

Closed as non-relevant to this project: we don't do any XML manipulation in Spring Integration. That's already a Spring Framework responsibility. 
Plus you got a workaround for your unit test if you don't want to re-write it.

**Closed by artembilan** 2022-01-03 16:09 UTC
Labels: status: waiting-for-reporter, type: bug
