### ISSUE TITLE
NPI Exposed in info log

### ISSUE THREAD

**Issue by brentleeper** [spring-projects/spring-integration#3222] opened 2020-03-17 21:50 UTC
**Affects Version(s):** \<Spring Integration version>
Current
---

In org.springframework.integration.handler.support.MessagingMethodInvokerHelper.fallbackToInvokeExpression(), the message is logged using LOGGER.info, this should be LOGGER.warn. 

Also, this log message currently fully exposes the contents of the ParametersWrapper 'parameters' in the INFO logs and I believe this is undesired, as parameters is exposing its state too openly for this logging level and should be split from the above into LOGGER.debug

**Comment by artembilan** [comment] 2020-03-18 15:07
The `WARN` is a bit lower severity than `INFO`. That means when you enable `INFO` for logging you are going to see `WARN`, too. So, your concern about logging level is not clear.
Also we select a level according some logic: there is no reason to make a `WARN` here because we are going to do a *fallback* therefore your program is not going to fail.

The parameter masking is kinda not related to this issue and there are many places where we print messages with their payload and headers.
If you wish we can make this message under `DEBUG`, but again: is this really only a place where you worry about your data exposure?

**Comment by brentleeper** [comment] 2020-03-18 15:11
Leaving the logging level at info for the message is agreeable. However, in my current use case, logging the payload and headers in the info log is exposing NPI in the log file. For now my work around is just to set the logger to off.

**Comment by brentleeper** [comment] 2020-03-18 15:12
NPI - Non Public Information

**Comment by artembilan** [comment] 2020-03-18 15:19
OK. Understandable.

So, we can treat this issue like:

Whenever we log a content of the message under `INFO`, consider to move such a possibly sensitive information under `DEBUG` level, leaving with an `INFO` just a generic note.

I don't say that we are going to do that because this is not a trivial task and we also throw exceptions in many places with the message caused an error. How to be over here then?

Wouldn't it be better to not have an INFO or DEBUG logging level for the framework and log reasonable messages using your own components ?

**Comment by brentleeper** [comment] 2020-03-18 15:31
I understand that this would be a large undertaking. But what you describe above is exactly what I am thinking and we do have logging in our own components. 

For now the work around is acceptable, but if there is an issue related to the framework it may be more difficult trace.

**Comment by artembilan** [comment] 2020-03-18 15:39
Well, for that reason an issue is going to be logged under `ERROR` or `WARN`. In most case of course it is going to be an exception with the whole stack trace to track the reason or so.

**Comment by artembilan** [comment] 2020-03-18 18:44
@garyrussell ,

I would like to hear your opinion about this issue.

Thanks

**Comment by garyrussell** [comment] 2020-03-18 18:56
Maybe ask Spring Framework to add:

```java
public interface MessageToStringFunction extends Function<Message<?>, String> {
}
```

and `setToStringFunction(MessageToStringFunction function)` to `GenericMessage` and our `MessageBuilder` can inject a user-supplied implementation into every message. That way the user can obfuscate/remove NPI.

??

**Comment by artembilan** [comment] 2020-03-18 19:13
Raised: https://github.com/spring-projects/spring-framework/issues/24727

**Comment by artembilan** [comment] 2024-11-05 20:23
Duplicate of https://github.com/spring-projects/spring-integration/issues/9416

**Closed by artembilan** 2024-11-05 20:23 UTC
Labels: status: on-hold-dependency
