### ISSUE TITLE
zookeeper in reactor is not work

### ISSUE THREAD

**Issue by MrWangGang** [spring-projects/spring-integration#9145] opened 2024-05-14 08:39 UTC
```
Mono.just("1").flatMap(e->{
        if(lockRegistry.obtain("xxx").tryLock()){
            lockRegistry.obtain("xxx").unlock();
        }
        return Mono.empty();
    })
```
Caused by: java.lang.IllegalMonitorStateException: You do not own the lock: /locks/xxx

but in no reactive program is working , i dont know why

**Comment by artembilan** [comment] 2024-05-15 15:27
You probably don't share something else in your sample.
The suggested code works:
```
	@Test
	void testGh9145() throws InterruptedException {
		ZookeeperLockRegistry lockRegistry = new ZookeeperLockRegistry(this.client);
		CountDownLatch lockUnlockedLatch = new CountDownLatch(1);
		Mono.just("1")
				.flatMap(e -> {
					if (lockRegistry.obtain("xxx").tryLock()) {
						lockRegistry.obtain("xxx").unlock();
						lockUnlockedLatch.countDown();
					}
					return Mono.empty();
				})
				.subscribe();

		assertThat(lockUnlockedLatch.await(10, TimeUnit.SECONDS)).isTrue();
	}
```

**Comment by MrWangGang** [comment] 2024-05-16 14:39
thanks,is working, but CountDownLatch in reactor is not good , i think ,we need reactor intergration zookeeper impl

**Comment by artembilan** [comment] 2024-05-16 14:44
The `CountDownLatch` is here just for unit test purpose.
Since we don't know what is your real code, your assumption about some specific implementation is not justified.

Here is a variant of that test without `CountDonwLatch`:
```
	@Test
	void testGh9145() {
		ZookeeperLockRegistry lockRegistry = new ZookeeperLockRegistry(this.client);
		Mono<String> testMono =
				Mono.just("1")
				.flatMap(e -> {
					if (lockRegistry.obtain("xxx").tryLock()) {
						lockRegistry.obtain("xxx").unlock();
						return Mono.just("unlocked");
					}
					return Mono.empty();
				});

		StepVerifier.create(testMono)
				.expectNext("unlocked")
				.verifyComplete();
	}
```

**Comment by MrWangGang** [comment] 2024-05-18 17:06
```
return reactiveZookeeperLock.tryLock()
                          .flatMap(locked->{
                              if(locked){
                                  GetDreamByIdDTO getDreamByIdDTO = GetDreamByIdDTO.builder().dreamId(skill.getDreamId()).build();
                                  return socialDreamApi.getDreamById(getDreamByIdDTO).switchIfEmpty(Mono.error(() -> new EventException(EB_ITEM_018)))
                                          .flatMap(dream -> {
                                              if (!DREM_UNFINISHED.equals(dream.getStatus())) {
                                                  return Mono.error(new EventException(EB_ITEM_019));
                                              }
                                              if (!user.getId().equals(dream.getUserId())) {
                                                  return Mono.error(new EventException(EB_ITEM_020));
                                              }
                                              if (!user.getId().equals(skill.getUserId())) {
                                                  return Mono.error(new EventException(EB_ITEM_027));
                                              }
                              
                                              skill.setAvailable(ITEM_AVAILABLE_FALSE);
                                              return iItemDreamSkillService.update(skill).then();
                                          });
                              }
                              return Mono.error(new EventException(EB_ITEM_035));
                          }).then(reactiveZookeeperLock.unlock());
```
                          
`then(reactiveZookeeperLock.unlock()); 
 is woring good,but      
` doFinally(fi->reactiveZookeeperLock.unlock());
`
java.lang.IllegalMonitorStateException: You do not own the lock: /_itemDreamSkill/_common/6648b53d55c114479c8e7904


why>>>>>????

**Comment by MrWangGang** [comment] 2024-05-20 01:36
help

**Comment by MrWangGang** [comment] 2024-05-20 01:36
@artembilan

**Comment by artembilan** [comment] 2024-05-20 02:27
It is still weekend over here in East cost of USA. I’ll come back to you tomorrow in my Monday’s morning.

**Comment by artembilan** [comment] 2024-05-20 15:14
The logic there in the `InterProcessMutex` is like this:
```
    public void release() throws Exception {
        /*
           Note on concurrency: a given lockData instance
           can be only acted on by a single thread so locking isn't necessary
        */

        Thread currentThread = Thread.currentThread();
        LockData lockData = threadData.get(currentThread);
        if (lockData == null) {
            throw new IllegalMonitorStateException("You do not own the lock: " + basePath);
        }
```

So, apparently that `doFinally(fi->reactiveZookeeperLock.unlock());` is done from a different thread than `then(reactiveZookeeperLock.unlock());`.

It is in fact not recommended to rely on `ThreadLocal` through Reactive Streams. Better to use Reactor context, but apparently that is not possible since `InterProcessMutex` is heavy-tied to `ThreadLocal`.

**Comment by MrWangGang** [comment] 2024-05-21 02:54
I understand, they are on different threads, and this issue might not be solvable. I'll just move the logic further down into the innermost flatMap, and that should solve the problem ，@artembilan  Perhaps you could provide a method like unlock(threadId) to unlock. Then, I could pass the threadId through contentView to unlock from the outside.

**Comment by MrWangGang** [comment] 2024-05-27 07:24
thanks

**Comment by artembilan** [comment] 2024-05-28 16:59
Closed as `Works as Designed`.

**Closed by artembilan** 2024-05-28 16:59 UTC
Labels: status: invalid
