### ISSUE TITLE
RQ: more convenient splitter shortcuts

### ISSUE THREAD

**Issue by bruto0** [spring-projects/spring-integration#2722] opened 2019-01-28 19:21 UTC
**Affects Version(s):** \5.0.4

It'd be nice to have an easy way to split a batch of messages containing batch headers into single messages with a single lambda or something like that

For example, if you use SI-Kafka message driven channel adapter with ListenerMode.BATCH, you receive a batch message with Kafka headers packed into a list and if you want to process them separately after that, you have to do something like:

    IntegrationFlows.from(Kafka.messageDrivenChannelAdapter(consumerFactory(), ListenerMode.batch, ...
    .split(new HeaderCopyingSplitter())
    ...

    // nothing like this out of the box, btw
    public class HeaderCopyingSplitter extends MethodInvokingSplitter {
        public HeaderCopyingSplitter() {
            super(new LambdaMessageProcessor(Function.identity(), Iterable.class));
        }
    
        @Override
        protected boolean shouldCopyRequestHeaders() {
            return true;
        }
    }

    private long getKafkaReceivedTimestampFromBatchHeaders(Message<?> msg) {
            List timestamps = msg.getHeaders().get(KafkaHeaders.RECEIVED_TIMESTAMP, List.class);
            int seqNumber = msg.getHeaders().get(IntegrationMessageHeaderAccessor.SEQUENCE_NUMBER, Integer.class);
            return (long) timestamps.get(seqNumber - 1);
        }

This is probably not an uncommon scenario, but dealing with it is kinda awkward
Maybe you can come up with an easier way of achieving the same effect

**Comment by bruto0** [comment] 2019-01-28 19:32
as a means to increase throughput
I use autocommit, too

**Comment by garyrussell** [comment] 2019-01-28 19:34
Can you explain how you believe it will increase throughput? When in record mode, the container and listener adapter will do exactly what your proposed splitter does. The container effectively "splits" the `ConsumerRecords<?, ?>` into individual records.

**Comment by bruto0** [comment] 2019-01-28 19:47
indeed it does, now that you made me look at the container

I remember that testing showed some increase, though - don't remember how large :)
guess it might have been due to something else

**Comment by artembilan** [comment] 2019-02-05 15:00
Well, I'm fully not sure that there is going to be some generic way to extract headers per item, unless we would allow to inject something like `BiFunction` for `requestMessage` and `sequence` as arguments and `Map` as a result.

On the other hand we always send all the headers to each splitted item. So, you need to access some aggregated headers per `sequence` you simply can do that in downstream `.enrichHeaders()`. 
This way you have a full control over the data and you have a freedom how to manipulate it.
If we introduce some contract to the `AbstractMessageSplitter`, you will have to sing it and still be frustrated one day when this contract can't cover your use-case.

**Comment by artembilan** [comment] 2019-04-25 17:25
Closing as *Works as Designed* since the request can be covered with an existing functionality with the proper *loosely coupled concern* honoring.

**Closed by artembilan** 2019-04-25 17:25 UTC
Labels: waiting-for-reporter, waiting-for-triage
