### ISSUE TITLE
Advisors are duplicated when starting and stopping adapter multiple times

### ISSUE THREAD

**Issue by eahamada** [spring-projects/spring-integration#1903] opened 2016-09-23 15:49 UTC
Hi,

When starting and stopping adapter multiple times, poller advices are added/duplicated to existing advices. I have setup  [this repository](https://github.com/eahamada/spring-integration-samples-basic-controlbus) :
#### To reproduce current behavior and expected behavior with maven
$ mvn -Dtest=org.springframework.integration.samples.controlbus.ControlBusDemoTest#current  test
$ mvn -Dtest=org.springframework.integration.samples.controlbus.ControlBusDemoTest#expected  test

Is there any other way to get expected behavior without clearing adviceChain ?

**Comment by garyrussell** [comment] 2016-09-23 15:53
Thanks for reporting this.

It's a bug - caused by https://jira.spring.io/browse/INT-3899

**Comment by artembilan** [comment] 2016-09-23 15:59
See https://jira.spring.io/browse/INT-4120

**Comment by garyrussell** [comment] 2016-09-23 18:32
Pull requests issued; we'll relase 4.3.3 asap.

**Comment by artembilan** [comment] 2016-09-28 22:16
Fixed via https://github.com/spring-projects/spring-integration/pull/1904 for `master` and  https://github.com/spring-projects/spring-integration/pull/1905 for `4.3.x`

**Closed by artembilan** 2016-09-28 22:16 UTC
