### ISSUE TITLE
Error: Unable to sync local directory

### ISSUE THREAD

**Issue by abufaarooq** [spring-projects/spring-integration#8783] opened 2023-10-31 15:29 UTC
**In what version(s) of Spring Integration are you seeing this issue?**

For example:

5.3.2.RELEASE

Between 4.3.15 and 5.2.5

**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by artembilan** [comment] 2023-10-31 15:31
@abufaarooq ,

you probably need to edit the issue to provide all the info required to determine the problem.
Otherwise this is going to be treated as spam and removed.
Thanks

**Comment by artembilan** [comment] 2023-10-31 15:34
Closed as duplicate of: https://github.com/spring-projects/spring-integration/issues/8784

**Closed by artembilan** 2023-10-31 15:34 UTC
Labels: type: bug, status: waiting-for-triage
