### ISSUE TITLE
SynchFeed is not being set as the source for SynchEntry within FeedEntryMessageSource

### ISSUE THREAD

**Issue by dwitherspoon** [spring-projects/spring-integration#2747] opened 2019-02-14 02:06 UTC
**Affects Version(s):** 5.1.2.RELEASE

---

When setting up an Integration Feed to pull from an RSS endpoint, the SynchEntry's source is not being set to the SourceFeed that it came from.  I tracked down the location within the FeedEntryMessageSource class in the populateEntryList() the entry never sets the source to the syndFeed before it is added to the list.  Therefore, when you are processing RSS feeds all of the SyndEntries that you get all have null for the source.

**Comment by artembilan** [comment] 2019-02-14 02:16
The logic there is like this:
```
	private void populateEntryList() {
		SyndFeed syndFeed = this.getFeed();
		if (syndFeed != null) {
			List<SyndEntry> retrievedEntries = syndFeed.getEntries();
			if (!CollectionUtils.isEmpty(retrievedEntries)) {
				boolean withinNewEntries = false;
				Collections.sort(retrievedEntries, this.syndEntryComparator);
				for (SyndEntry entry : retrievedEntries) {
					Date entryDate = getLastModifiedDate(entry);
					if ((entryDate != null && entryDate.getTime() > this.lastTime)
							|| (entryDate == null && withinNewEntries)) {
						this.entries.add(entry);
						withinNewEntries = true;
					}
				}
			}
		}
	}
```
As you see we do nothing with those entries, unless sort and filter.
So, looks like underlying library doesn't do the proper logic to populate a `source` back on the entries during parsing RSS.
Can you debug down to the `com.rometools:rome` and see what is going on there in your case? Why doesn't that provide a source for us?

I won't mind to fix it here as a workaround, but this doesn't sound like fault of this project.
I just want to properly distinguish responsibility and don't poll too much to the Framework level when it has to be done in our dependency.

Thanks for understanding!

**Comment by dwitherspoon** [comment] 2019-02-14 03:05
That is a great point and I will find some time to dive into the syndFeed.getEntries() to find out why it is not assigning the source within there.  You are right that originally I was doing a workaround by assigning the source to the entry before it was added to the list.  I will see what I can find out within the code within the Rome dependency.

**Comment by artembilan** [comment] 2019-08-22 20:46
@dwitherspoon ,

Any update on the matter?

May be we can close it as "Cannot reproduce"?

**Comment by artembilan** [comment] 2020-04-30 15:56
Closed as `Invalid` with no activity from the reporter.

Feels free to reopen if there are some news what and how could be adapted in this project.

Thank you!

**Closed by artembilan** 2020-04-30 15:56 UTC
Labels: status: waiting-for-reporter, status: waiting-for-triage
