### ISSUE TITLE
LockInterceptor and VariableBindingGroovyObjectCustomizerDecorator do not end with linefeed

### ISSUE THREAD

**Issue by strkkk** [spring-projects/spring-integration#3149] opened 2020-01-22 10:07 UTC
During fix of https://github.com/checkstyle/checkstyle/issues/4074 we discovered 2 files in spring-integration that have CRLF at the end instead of LF which is supposed to be line separator.

spring-integration/spring-integration-groovy/src/main/java/org/springframework/integration/groovy/VariableBindingGroovyObjectCustomizerDecorator.java

spring-integration/spring-integration-jdbc/src/test/java/org/springframework/integration/jdbc/LockInterceptor.java

Full report with details
https://strkkk.github.io/checkstyle/4074/spring-integration/index.html
Checkstyle PR https://github.com/checkstyle/checkstyle/pull/7500

**Comment by artembilan** [comment] 2020-01-22 15:20
That's interesting. We have this check:
```
<module name="NewlineAtEndOfFile">
	<property name="lineSeparator" value="lf"/>
</module>
```
and it doesn't fail for us.
More over I develop on Windows and check out from Git with `CRLF` and check in with `LF`, but again: Checkstyle doesn't fail for us on Linux with our CI nor on Mac of other developers.

So, how to make it fail, please?
Anyway any pointers how to fix? It doesn't show me anything as difference to push upstream, when I try to apply `CRLF` for the whole file.

Thank you!

**Comment by garyrussell** [comment] 2020-01-22 15:31
<img width="220" alt="Screen Shot 2020-01-22 at 10 30 34 AM" src="https://user-images.githubusercontent.com/483832/72907676-4a0fcd80-3d02-11ea-942e-f16e619f81b5.png">

Both files have newlines at the end, but they are incorrectly checked in to GitHub with DOS newlines (CRLF)>

**Comment by strkkk** [comment] 2020-01-22 15:42
@artembilan You have no error there because your checkstyle version has a bug, which is fixed in PR.
I ran analysis by fixed version and problem was discovered

**Comment by artembilan** [comment] 2020-01-22 15:45
>  checked in to GitHub with DOS newlines

Can you fix that, Gary, please?

Looks like I can't do that from my side 😄

**Comment by garyrussell** [comment] 2020-01-22 16:11
Done.

**Closed by garyrussell** 2020-01-22 16:11 UTC
Labels: waiting-for-reporter

**Comment by rnveach** [comment] 2020-01-22 16:12
> So, how to make it fail, please?

This is a bug in checkstyle which we are attempting to fix for a new release.

You can see the issue at https://github.com/checkstyle/checkstyle/issues/4074 . The problem is that even though you defined your line endings as `\n`, checkstyle does not check it is only `\n` and thus lets `\r\n` through.

We were alerted to the issue with your project since our CI is connected to your project and uses it as regression on new fixes introduced in checkstyle.
