### ISSUE TITLE
NullPointerException with aspectj advice in spring boot

### ISSUE THREAD

**Issue by srinivasanr1989** [spring-projects/spring-integration#2142] opened 2017-05-04 17:45 UTC
Hi Team,

I have a Spring Integration application that processes messages from a MQ and posts it to another.
Am trying to migrate to Spring Boot. 
Snippets from the setup as below ,
```
<parent>
		<groupId>org.springframework.boot</groupId> 
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.2.RELEASE</version>`
</parent>
```

aspectjweaver version - 1.8.9

Application file,

```
@SpringBootApplication(exclude = { JmsAutoConfiguration.class })
@ComponentScan(basePackages = { "com.abc.xxx" })
public class Application {
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}
```

ApplicationConfiguration:

```
@Configuration
@ImportResource(locations = { "classpath:accountingContext.xml" })
public class ApplicationConfiguration {
}
```

Everything works fine and the application starts without any errors.
But when the application processes any message from the queue, I get the following error,

```
Caused by: org.springframework.messaging.MessageDeliveryException: failed to send Message to channel null'; nested exception is java.lang.NullPointerException
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:449)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:373)
	at com.ntrs.geh.message.job.RequestTimeoutCheckerCronJob.execute(RequestTimeoutCheckerCronJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:406)
	... 4 common frames omitted
```

Upon debugging, I found that the datatypes reference is `null` in the following line,
```
	if (this.datatypes.length > 0)` in the `AbstractMessageChannel
```
After referring to this thread
https://github.com/spring-cloud/spring-cloud-stream/issues/881

I removed the aspect defined on the channel below and it started to work fine.
```
<tx:advice id="txAdvice" transaction-manager="dataSourceTransactionManager">
	<tx:attributes>
		<tx:method name="send" />
	</tx:attributes>
</tx:advice>
<int:channel id="requestSchemaValidationChannel" />
```
```
<aop:config>
	<aop:advisor advice-ref="txAdvice" pointcut="bean(requestSchemaValidationChannel)" />
</aop:config>

```

The same configuration used to work before we migrated to spring boot.
Can you please let me know if am doing some thing wrong or if there is a workaround ?

**Comment by garyrussell** [comment] 2017-05-04 18:03
It's impossible for that field to be `null` in a "normal" channel. It is initialized to an empty array and even if the setter is called, a null value becomes an empty array.

It looks like the channel instance is being created using `Unsafe` or similar.

If you can provide a small test case that reproduces the issue, we can take a look.

BTW, GitHub issues is not the place for questions like this; we use StackOverflow for that. Issues are for bugs or feature requests.

**Comment by artembilan** [comment] 2017-05-04 18:07
Absolutely identical problem: https://github.com/spring-cloud/spring-cloud-stream/issues/881

The root of cause is `proxyTargetClass = true`. Try to use normal JDK proxying.

**Comment by artembilan** [comment] 2017-05-04 18:09
`proxy-target-class="false"` is there for you on the `<aop:config>`

**Comment by garyrussell** [comment] 2017-05-04 18:16
I reproduced it with a small test case and the `proxy-target-class` makes no difference (true or false). Investigating...

**Comment by srinivasanr1989** [comment] 2017-05-04 18:16
Thanks @artembilan , I will try that and get back.
@garyrussell : My apologies, I created an issue as I saw a similar one associated with AspectJ proxy.

**Comment by garyrussell** [comment] 2017-05-04 18:20
For some reason I'm still getting a CGLIB proxy instead of a JDK proxy, even with false.

**Comment by srinivasanr1989** [comment] 2017-05-04 18:21
yes, setting proxy-target-class doesn't solve. 
@garyrussell - yes, I observed the same while debugging the instance.

**Comment by garyrussell** [comment] 2017-05-04 18:30
It looks like something in boot is forcing the use of a CGLib proxy; it also works for me when I load the context outside of a boot app (I get a JDK proxy).

**Comment by garyrussell** [comment] 2017-05-04 18:34
Here's the fix; add ...

    spring.aop.proxy-target-class=false

to `application.properties`

**Comment by srinivasanr1989** [comment] 2017-05-04 18:36
Thanks @garyrussell , I will try this and get back.

**Comment by garyrussell** [comment] 2017-05-04 18:38
This doesn't see to be the expected default behavior, though - see `AopAutoConfiguration` javadocs (and conditional beans).

**Comment by garyrussell** [comment] 2017-05-04 18:43
- @ConditionalOnProperty (spring.aop.auto=true) matched (OnPropertyCondition)

Something is setting it to `true`.

**Comment by garyrussell** [comment] 2017-05-04 18:57
AopAutoConfiguration.JdkDynamicAutoProxyConfiguration matched:
          - @ConditionalOnProperty (spring.aop.proxy-target-class=false) matched (OnPropertyCondition)

Strange; the auto config report says it's false.

**Comment by garyrussell** [comment] 2017-05-04 19:15
It's caused by `TransactionAutoConfiguration` - it's [fixed in boot 2.0](https://github.com/spring-projects/spring-boot/issues/8786).

**Closed by garyrussell** 2017-05-04 19:15 UTC

**Comment by srinivasanr1989** [comment] 2017-05-04 19:48
For some reason, it didn't work even after setting `spring.aop.proxy-target-class=false`
I made it to work by excluding,
```
TransactionAutoConfiguration.class,
DataSourceAutoConfiguration.class,
DataSourceTransactionManagerAutoConfiguration.class
``` 

Thank you so much @garyrussell  @artembilan  for the help.

**Comment by rokii** [comment] 2017-06-27 02:17
@srinivasanr1989 can you share how to exclude classes from aop-auto-proxy?

**Comment by artembilan** [comment] 2017-06-27 02:33
That's not so easy for global AspectJ Proxy factory. Consider to upgrade to the 4.3.10 which comes with the Boot 1.5.4: https://jira.spring.io/browse/INT-4270.

If that isn't your case, please, share stack trace and will see what to fix else in the Framework.
