### ISSUE TITLE
JAXB Unmarshaller not unlocking after failure

### ISSUE THREAD

**Issue by lafual** [spring-projects/spring-integration#3238] opened 2020-04-02 11:40 UTC
Hi,
In Windows I am reading a file that "should" contain XML using `@InboundChannelAdapter FileReadingMesageSource` and passing on to `@Transformer UnmarshallingTransformer`.

If the un-marshall works, the correct object is forwarded. When the XML is invalid or not the file didn't contain XML a `MessageTransformerException` is forwarded.

When the un-marshall is successful, the incoming file is un-locked and I can remove it from the incoming directory. However, when I get a `MessageTransformerException` the file's lock is not released. When I try to move it get `java.nio.file.FileSystemException: The process cannot access the file because it is being used by another process`

In the `FileReadingMessageSource` I have tried without `setLocker`, `setLocker` with `NIOFileLocker` and an implementation of `FileLocker` which creates an additional file with a `.locked` extension. None of these solutions work.

I am using the following to Transform;

```
@Bean
public Jaxb2Marshaller unmarshaller() {
   Jaxb2Marshaller x = new Jaxb2Marshaller();
   x.unmarshaller(MyClass.class);
   return x;
}

@Bean
@Transformer
public UnmarshallingTranformer umt() {
   return new UnmarshallingTransformer(unmarshaller());
}
```

How do I cause the lock to be released?

Shouldn't the transformer somehow share/re-use the lock of the original file reader? It seems as if it is using its own locking and not releasing after failure.

**Comment by artembilan** [comment] 2020-04-02 15:57
Confirmed.

Now need to figure out how to fix...

**Comment by artembilan** [comment] 2020-04-02 16:48
OK. I found that `xcerces` opens an `InputStream` for the file `XMLEntityManager`  to build an `Entity.ScannedEntity`.
This entity is closed in case of `XMLEntityManager.endEntity()` when we have already parsed the current entity and ready to go for the next one, what is not a case for us because of that failure during parsing.

It was probably fixed in some later Java version, but it really still fails for me on Java 8 on Windows...

I will try to workaround it with an explicit `InputStream` reading in the `UnmarshallingTranformer` instead of delegation to the target JaxB impl...

**Comment by artembilan** [comment] 2020-04-02 17:09
The fix is not reviewed yet.

**Comment by artembilan** [comment] 2020-04-03 01:59
Fixed according merged PR with an appropriate back-port to all the supported versions.

**Closed by artembilan** 2020-04-03 01:59 UTC
Labels: backport 4.3.x, backport 5.1.x, backport 5.2.x, in:xml, type: bug

**Comment by lafual** [comment] 2020-04-03 08:24
Thanks very much for the fast turn-around!

FYI - I was using Java 10 (the 'last chance saloon' before Java 11 and modules), not 8.

I managed to work around the problem by adding a `FileToStringTransformer` before the `UnmarshallingTransformer`.

**Comment by artembilan** [comment] 2020-04-03 14:47
Thanks, @lafual , for feedback! So, sounds like the problem remains in the Java 10 as well, but anyway we can't rely on the latest Java version because of backward compatibility with existing application based on our Spring artifacts.

Nice trick with the `FileToStringTransformer` though! 👍
