### ISSUE TITLE
@IntegrationComponentScan does't  work ,though the value of useDefaultFilters is set false, @MessagingGateway compoment is still Scaned

### ISSUE THREAD

**Issue by shyding** [spring-projects/spring-integration#3375] opened 2020-09-03 03:15 UTC
**In what version(s) of Spring Integration are you seeing this issue?**

For example:

5.3.2.RELEASE

Between 4.3.15 and 5.2.5

**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by artembilan** [comment] 2020-09-08 17:17
Please, start from StackOverflow with much more info.

We will see then together if there is really a bug.

You should follow instructions we ask in the issue template.
Right now there are really missing many important details which would let us to reproduce and confirm or not.

I'll back to this issue tomorrow and if there is still no requested info, I close it as `Invalid`.

Thanks for understanding

**Comment by artembilan** [comment] 2020-09-09 22:25
Well, probably you suffer here from the fact that default `@IntegrationComponentScan` provided by Spring Boot auto-configuration has its own effect fully ignoring your custom one.

You should consider to rely on the `basePackages` for auto-configuration in Spring Boot instead. See `@AutoConfigurationPackage`.

Probably there is really nothing we can do here since Spring doesn't prevent us to provide several `@ComponentScan` and, therefore, `@IntegrationComponentScan`.

Closing as `Works as Designed`.

**Closed by artembilan** 2020-09-09 22:25 UTC
Labels: status: waiting-for-reporter, type: bug
