### ISSUE TITLE
AbstractInboundFileSynchronizingMessageSource should inject beanFactory on synchronizer

### ISSUE THREAD

**Issue by dturanski** [spring-projects/spring-integration#3365] opened 2020-08-19 11:55 UTC
**In what version(s) of Spring Integration are you seeing this issue?**
5.3.2.RELEASE

**Describe the bug**

I get a WARN with stack trace in SFTP Supplier function tests:

```
07:53:15.448 [main] WARN  o.s.i.expression.ExpressionUtils - Creating EvaluationContext with no beanFactory
java.lang.RuntimeException: No beanFactory
	at org.springframework.integration.expression.ExpressionUtils.createStandardEvaluationContext(ExpressionUtils.java:90)
	at org.springframework.integration.file.remote.synchronizer.AbstractInboundFileSynchronizer.afterPropertiesSet(AbstractInboundFileSynchronizer.java:299)
```

It seems like the fix would be here:

https://github.com/spring-projects/spring-integration/blob/master/spring-integration-file/src/main/java/org/springframework/integration/file/remote/synchronizer/AbstractInboundFileSynchronizingMessageSource.java#L195

**Sample**

https://github.com/spring-cloud/stream-applications/blob/master/functions/supplier/sftp-supplier/src/test/java/org/springframework/cloud/fn/supplier/sftp/SftpSupplierApplicationTests.java

**Comment by artembilan** [comment] 2020-08-19 14:15
One of our rules in Spring Integration project is to not mutate an injected objects.
See that `AbstractInboundFileSynchronizingMessageSource`:
```
public AbstractInboundFileSynchronizingMessageSource(AbstractInboundFileSynchronizer<F> synchronizer) {
```
So, if you inject a `synchronizer` into this one, you are responsible for its proper initialization.

According to your stack trace, it looks like `AbstractInboundFileSynchronizer.afterPropertiesSet()` is called anyway. I wonder how that hapened in your configuration that `synchronizer` is not a bean for a `BeanFactoryAware`, but its `afterPropertiesSet()` is still called.

Any chances to see some configuration and more stack trace?

I don't mind if we have an issue somewhere to fix, but that definitely is not going to be about mutating an externally configured injection.

**Comment by dturanski** [comment] 2020-08-19 15:46
Not sure. I don't reference it in my code.

**Comment by artembilan** [comment] 2020-08-19 19:11
Turned out a target configure was wrong a bit.
The complex `IntegrationComponentSpec` like an `SftpInboundChannelAdapterSpec` in our case may implement a `ComponentsRegistration`, which in our case produces the mentioned `synchronizer` for bean registration.

Fixed a target code returning a `spec` as a bean instead.
Since an `IntegrationComponentSpec` is a `FactoryBean` by itself, it let us to produce a desired bean, but making the `spec` visible gives an `IntegrationFlowBeanPostProcessor` opportunity to process `ComponentsRegistration` from the spec properly.

Closed as `Works as Designed`

**Closed by artembilan** 2020-08-19 19:11 UTC
Labels: status: waiting-for-reporter, type: bug
