### ISSUE TITLE
missing metrics after update from 5.3.2 to 5.3.3

### ISSUE THREAD

**Issue by agebhar1** [spring-projects/spring-integration#3420] opened 2020-11-04 18:51 UTC
Update from 5.3.2 to 5.3.3 (via Spring Boot Update from 2.3.4 to 2.3.5)

**Describe the bug**

Metrics for channels etc. are not provided by Prometheus endpoint `/actuator/prometheus` anymore.

**To Reproduce**

Metrics are missing if

```
@Bean
public MeterRegistry meterRegistry(PrometheusMeterRegistry registry) {
  return registry;
}
```

is not present (config/ApplicationConfiguration.java). The bean must be added explicit after update to 5.3.3 to enable metrics again.

**Expected behavior**

Not yes sure.

**Sample**

A almost simple sample is from a presentation [demo](https://github.com/agebhar1/slides-202005-lej-software-crafter-eip-lightning/tree/master/demo)

**Comment by artembilan** [comment] 2020-11-04 19:12
Your sample is too complicated to play with on our side.

I'll try to come up with something very plain and we'll come back to you later.

**Comment by agebhar1** [comment] 2020-11-04 19:20
I can provide a plain example tomorrow if it helps.

**Comment by artembilan** [comment] 2020-11-04 19:25
Sure! That would be great!
I even think we don't need any complex flows.
Only your concern that there are no metrics for Spring Integration if that are no `MeterRegistry` bean.

I'm fully sure it is related to this: https://github.com/spring-projects/spring-integration/commit/d60f23549c8b807bb0805948d2f40a07bba0c931, but as far as I know Spring Boot auto-configures for us a `CompositeMeterRegistry` as a `@Primary` bean anyway.

So, yeah, as simple reproducable sample would be great and we will see at what point we are missing meters registration in Spring Integration.

**Comment by agebhar1** [comment] 2020-11-04 20:02
Okay, I will provide such a simple sample (tomorrow).

**Comment by agebhar1** [comment] 2020-11-05 17:47
Hello @artembilan a simple sample is set up https://github.com/agebhar1/si-3420-demo

**Comment by agebhar1** [comment] 2020-11-05 17:57
The problem is https://github.com/spring-projects/spring-integration/blob/1dd0315156de848309e09f14a250fb08e3b29260/spring-integration-core/src/main/java/org/springframework/integration/support/management/micrometer/MicrometerMetricsCaptorRegistrar.java#L52-L65

Without an explicit bean of type `MeterRegistry` the condition fails.

**Comment by artembilan** [comment] 2020-11-05 18:38
Thank you!

I will look into this shortly

**Comment by artembilan** [comment] 2020-11-05 20:11
It looks like we also need to fix Spring Boot and make an `IntegrationAutoConfiguration` to be auto-configured **after** a `CompositeMeterRegistryAutoConfiguration`. Or vise-versa.

For time being the workaround is:

Place into a `resources/META-INF` the `spring-autoconfigure-metadata.properties` file with content:
```
org.springframework.boot.actuate.autoconfigure.metrics.CompositeMeterRegistryAutoConfiguration.AutoConfigureBefore=org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration
```

This way Spring Boot builds for us its `MeterRegistry` bean and only after that `IntegrationAutoConfiguration.IntegrationManagementConfiguration` does its job with the mentioned `MicrometerMetricsCaptorRegistrar` logic. So, the condition `registry.containsBeanDefinition(MicrometerMetricsCaptor.MICROMETER_CAPTOR_NAME)` turns `true` and meters for Spring Integration components are registered with the Prometheus.

Now all your tests are passing, even without that custom `register` configuration property and those `MeterRegistry` explicit beans.

**Comment by agebhar1** [comment] 2020-11-06 18:19
Thank you for the instant help. The proposed workaround is truly smart and I mentioned it on the sample project. All tests pass now.

**Comment by artembilan** [comment] 2020-11-06 19:03
@agebhar1 ,

 thanks for confirmation, but for more cleaner picture consider to remove those explicit `MeterRegistry` from your configuration and don't use `register` property in the tests.

I'll see with Spring Boot team what we can do over there.

**Comment by agebhar1** [comment] 2020-11-08 17:11
@artembilan I updated the `workaround` branch accordingly.

Thank you.

**Comment by artembilan** [comment] 2020-11-09 17:02
@agebhar1 ,

I was managed to add the fix into Spring Boot: https://github.com/spring-projects/spring-boot/pull/24095

**Comment by agebhar1** [comment] 2020-11-09 18:08
Great news @artembilan - thank you.

**Comment by artembilan** [comment] 2020-12-01 16:57
The relevant Spring Boot PR has been merged and back-ported.

Closing this one as a part of respective upcoming releases of Spring Integration.

**Closed by artembilan** 2020-12-01 16:57 UTC
Labels: backport 5.2.x, backport 5.3.x, in: core, type: bug

**Comment by agebhar1** [comment] 2020-12-01 17:04
Thank you @artembilan!
