### ISSUE TITLE
Can't use HttpRequestExecutingMessageHandler directly without preparing an ApplicationContext

### ISSUE THREAD

**Issue by tombyong** [spring-projects/spring-integration#3018] opened 2019-08-07 01:14 UTC
https://github.com/spring-projects/spring-integration/blob/eac33d3132871014db380ac489ac8d27ec08d32e/spring-integration-http/src/main/java/org/springframework/integration/http/outbound/AbstractHttpRequestExecutingMessageHandler.java#L538

You are required to prepare a stub `ApplicationContext` when you are trying to use `HttpRequestExecutingMessageHandler` directly, while trying to resolve the response type using full class name. 

Or else you are getting `NullPointerException`. Using `class` directly has no issue.

**Comment by artembilan** [comment] 2019-08-07 01:35
That's correct. Because such a component has not been designed to work outside of Spring `ApplicationContext`. 
I guess it is not so hard to fix this exact issue as a fall back to the context `ClassLoader`, but you are going to have more problems in the future if you are intended to use Spring components outside of Spring.

Please, reconsider a design for your solution.
You are really free to borrow solutions from our components since it is an Open Source, but it should really be better to align your design with Spring implementation for dependency injection pattern.

Closing as *Works as Designed*

**Comment by tombyong** [comment] 2019-08-08 01:36
Understand the design, it doesn't need a fix to use the context class loader.

It would be good to throw a meaningful message before using the `ApplicationContext`.
Just like `BeanFactoryChannelResolver` checking for BeanFactory existence.

Thanks for your time.

**Comment by garyrussell** [comment] 2019-08-08 13:28
Agreed; we should not NPE; we can add an assert during initialization.

**Closed** 2019-08-08 20:20 UTC
Labels: type: enhancement

**Comment by tombyong** [comment] 2019-08-13 06:44
Thanks @garyrussell
