### ISSUE TITLE
MQTT broker automatically getting disconnected

### ISSUE THREAD

**Issue by bbbalabhaskar** [spring-projects/spring-integration#1983] opened 2016-11-24 06:44 UTC
I am trying to connect to MQTT Mosquitto broker using spring integration. Server is automatically getting disconnected to MQTT broker and trying to connect again, process going on again and again.

here is XML configuration:

```xml
<bean id="clientFactory"
		class="org.springframework.integration.mqtt.core.DefaultMqttPahoClientFactory">
		<property name="userName" value="${mqtt.username}"/>
		<property name="password" value="${mqtt.password}"/>
	</bean>

<bean id="mqttMessageHandler"
			class="com.demo.server.application.handlers.MQTTInboundMessageHandler"/>
	
	<bean id="errorMessageLogger" class="com.demo.server.application.logger.ErrorLogger"/>
	
	<init-integration:channel id="output"/>
	<init-integration:channel id="errorChannel"/>
	
	<int-mqtt:message-driven-channel-adapter id="mqttInbound"
		client-id="${mqtt.default.client.id}"
		url="${mqtt.url}"
		topics="hello/world"
		client-factory="clientFactory"
		channel="output"
		error-channel="errorChannel"
		qos="2"/>
		
	<init-integration:service-activator
		input-channel="errorChannel"
		ref="errorMessageLogger"/>
		
	<init-integration:service-activator 
		input-channel="output"
		ref="mqttMessageHandler"/>
```

I dont know if it a issue or my problem I am using spring 4.2.2.RELEASE.

Here is the log I am getting.
```log
12:09:11.803 [task-scheduler-1] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Connected and subscribed to [hello/world]
Connected and subscribed to [hello/world]
12:09:12.057 [MQTT Rec: 123123123] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Lost connection:Connection lost; retrying...
12:09:12.058 [task-scheduler-1] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Attempting reconnect
12:09:12.314 [task-scheduler-2] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Connected and subscribed to [hello/world]
Connected and subscribed to [hello/world]
Connected and subscribed to [hello/world]
12:09:12.585 [MQTT Rec: 123123123] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Lost connection:Connection lost; retrying...
12:09:12.585 [task-scheduler-3] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Attempting reconnect
12:09:12.888 [task-scheduler-1] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Connected and subscribed to [hello/world]
Connected and subscribed to [hello/world]
12:09:13.119 [MQTT Rec: 123123123] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Lost connection:Connection lost; retrying...
12:09:13.119 [task-scheduler-2] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Attempting reconnect
12:09:13.375 [task-scheduler-3] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Connected and subscribed to [hello/world]
Connected and subscribed to [hello/world]
Connected and subscribed to [hello/world]
12:09:13.650 [MQTT Rec: 123123123] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Lost connection:Connection lost; retrying...
12:09:13.651 [task-scheduler-4] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Attempting reconnect
12:09:13.919 [task-scheduler-2] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Connected and subscribed to [hello/world]
Connected and subscribed to [hello/world]
12:09:14.183 [MQTT Rec: 123123123] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Lost connection:Connection lost; retrying...
12:09:14.183 [task-scheduler-1] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Attempting reconnect
12:09:14.451 [task-scheduler-4] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Connected and subscribed to [hello/world]
Connected and subscribed to [hello/world]
Connected and subscribed to [hello/world]
12:09:14.717 [MQTT Rec: 123123123] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Lost connection:Connection lost; retrying...
12:09:14.717 [task-scheduler-5] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Attempting reconnect
12:09:14.974 [task-scheduler-1] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Connected and subscribed to [hello/world]
Connected and subscribed to [hello/world]
12:09:15.250 [MQTT Rec: 123123123] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Lost connection:Connection lost; retrying...
12:09:15.250 [task-scheduler-3] DEBUG o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Attempting reconnect
```

in the demo I used iot.eclipse.org broker.

**Comment by garyrussell** [comment] 2016-11-24 15:03
The "Lost connection: ...." message is emitted when the paho client calls the `connectionLost()` method so we're simply responding to that - presumably because the server closed the connection for some reason. I suggest you look at the server logs and/or look at the network traffic with wireshark or similar.

You could also try setting DEBUG logging for `org.eclipse.paho` in your app; it might provide more information. For example, when I stop the broker, I see this message...

    09:58:39.524 [MQTT Rec: siSampleConsumer] DEBUG o.e.p.c.mqttv3.internal.ClientState - siSampleConsumer: reason Connection lost (32109) - java.io.EOFException

**Comment by bbbalabhaskar** [comment] 2016-11-25 08:57
MQTT broker is working fine. I don't know the reason behind it but problem is resolved when I change web.xml configuration from 


```xml
	<servlet>
		<servlet-name>spring</servlet-name>
		<servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
		<load-on-startup>1</load-on-startup>
		<async-supported>true</async-supported>
	</servlet>
	<servlet-mapping>
		<servlet-name>spring</servlet-name>
		<url-pattern>/rest/*</url-pattern>
	</servlet-mapping>
	
```

to

```xml
         <servlet>
		<servlet-name>spring</servlet-name>
		<servlet-class>org.springframework.data.rest.webmvc.RepositoryRestDispatcherServlet
		</servlet-class>
		<load-on-startup>1</load-on-startup>
		<async-supported>true</async-supported>
	</servlet>
	<servlet-mapping>
		<servlet-name>spring</servlet-name>
		<url-pattern>/rest/*</url-pattern>
	</servlet-mapping>

```

**Comment by artembilan** [comment] 2016-11-28 16:48
Fully unclear how that change makes some difference, because the last one is just an extension of the first one: https://github.com/spring-projects/spring-data-rest/blob/master/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/RepositoryRestDispatcherServlet.java.

I think the mistake is somewhere in other place. Maybe really just because you try to get access to the Spring Data REST resource but it isn't exposed because there was no `RepositoryRestDispatcherServlet`.

Anyway if you find it as a solution, let's close this ticket!

Otherwise provide, please, more info what we should do from our side, if you think that the problem is there in the Spring Integration components.

**Comment by bbbalabhaskar** [comment] 2016-11-29 05:42
Please close the ticket if I find something wrong I will request to open it again, Thanks.

**Closed** 2016-11-29 14:04 UTC

**Comment by sonikrish26** [comment] 2017-12-22 08:03
[MQTT Rec: ClientId] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter - Lost connection:Connection lost; retrying...

This error comes when another subscriber is present for different topic and have the same client id. change the client id rebuild the project and then try to run again.

**Comment by garyrussell** [comment] 2017-12-22 14:06
That is correct; client ids must be unique for all clients connected to a broker, regardless of the topics.
