### ISSUE TITLE
Channel name being passed instead of actual channel

### ISSUE THREAD

**Issue by abdulbeard** [spring-projects/spring-integration#2263] opened 2017-10-11 20:47 UTC
I have had trouble getting access to the actual gatherResultChannel using just the name, unlike the replyChannel (which is the object itself).
https://github.com/spring-projects/spring-integration/blob/00807d47e2880e780b1430c3aba3a588490572da/spring-integration-core/src/main/java/org/springframework/integration/scattergather/ScatterGatherHandler.java#L140

Wouldn't it be better to just do:
```
		Message<?> scatterMessage = getMessageBuilderFactory()
				.fromMessage(requestMessage)
				.setHeader(GATHER_RESULT_CHANNEL, gatherResultChannel)
				.setReplyChannel(this.gatherChannel)
				.build();
```
so the actual channel is accessible to each subscriber to put their result into?

**Comment by artembilan** [comment] 2017-10-11 21:00
This is an internal channel for bridging logic from the gatherer to the output:
```
PollableChannel gatherResultChannel = new QueueChannel();

Object gatherResultChannelName = this.replyChannelRegistry.channelToChannelName(gatherResultChannel);

Message<?> scatterMessage = getMessageBuilderFactory()
		.fromMessage(requestMessage)
		.setHeader(GATHER_RESULT_CHANNEL, gatherResultChannelName)
		.setReplyChannel(this.gatherChannel)
		.build();

this.messagingTemplate.send(this.scatterChannel, scatterMessage);

Message<?> gatherResult = gatherResultChannel.receive(this.gatherTimeout);
if (gatherResult != null) {
	return gatherResult;
}
```
Not sure why would someone deal with that...

You can restore it into the object via that `HeaderChannelRegistry` though.
Its conversion to string is done intentionally because of serialization issue during network communication to let end-developer to avoid `header-channels-to-string` step: https://docs.spring.io/spring-integration/docs/4.3.12.RELEASE/reference/html/messaging-transformation-chapter.html#header-channel-registry

That is done intentionally because

**Comment by artembilan** [comment] 2017-10-17 01:02
Closed as "Works as Designed" after reporter reaction to the answer.

**Closed by artembilan** 2017-10-17 01:02 UTC
