### ISSUE TITLE
Poller annotation with cron expression should support a special disable character

### ISSUE THREAD

**Issue by Somebody25** [spring-projects/spring-integration#3371] opened 2020-08-26 07:14 UTC
**Expected Behavior**

`@Poller(cron = "-")`
should disable the poller so that the annotated `InboundChannelAdapter` for example, is never executed.

**Current Behavior**

An `IllegalArgumentException` is thrown:

```
java.lang.IllegalArgumentException: Cron expression must consist of 6 fields (found 1 in "-")
	at org.springframework.scheduling.support.CronSequenceGenerator.parse(CronSequenceGenerator.java:273)
	at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:98)
	at org.springframework.scheduling.support.CronSequenceGenerator.<init>(CronSequenceGenerator.java:85)
	at org.springframework.scheduling.support.CronTrigger.<init>(CronTrigger.java:45)
	at org.springframework.integration.config.annotation.AbstractMethodAnnotationPostProcessor.trigger(AbstractMethodAnnotationPostProcessor.java:487)
...
```

**Context**

This would be useful if the `Poller` is configured by a property, so one could disable it without a direct code change.
For example `@Poller(cron = "${my.cron.property}")`

The `@Scheduled` annotation has a similar behavior by permitting '-' as a special disable character which prevents the task from being scheduled in the `ScheduledTaskRegistrar`.

My current workaround is to add a `@ConditionalOnExpression` to my `@InboundChannelAdapter` to check if the property is set to ' -'

**Comment by garyrussell** [comment] 2020-08-26 14:56
You can achieve the behavior you desire by setting `autoStartup` to `false` on the inbound channel adapter.

**Comment by artembilan** [comment] 2020-08-26 16:25
I concur with @garyrussell : there is no reason in such an extra logic since every endpoint has that `autoStartup` option:

```
/**
	 * The {@link org.springframework.context.SmartLifecycle} {@code autoStartup} option.
	 * Can be specified as 'property placeholder', e.g. {@code ${foo.autoStartup}}.
	 * Defaults to {@code true}.
	 * @return the auto startup {@code boolean} flag.
	 */
	String autoStartup() default "";
```

so, when you don't want to poll at all, you just provide a `false` for this option.

See docs for more info: https://docs.spring.io/spring-integration/docs/5.3.2.RELEASE/reference/html/configuration.html#annotations

> Starting with version 4.0, all messaging annotations provide `SmartLifecycle` options (`autoStartup` and `phase`) to allow endpoint lifecycle control on application context initialization.

Closing as `Works as Designed`.

**Closed by artembilan** 2020-08-26 16:25 UTC
Labels: status: waiting-for-reporter, type: enhancement
