### ISSUE TITLE
Elasticsearch channel adapter & gateway addition

### ISSUE THREAD

**Issue by ipanimnim** [spring-projects/spring-integration#3774] opened 2022-04-09 16:52 UTC
**Expected Behavior**
There's should be Elasticsearch support in Spring Integration. Reactive & non Reactive (by implementing reactively and using `.block()`). Spring Data Elasticsearch can help a lot.

**Current Behavior**
As @artembilan said: "Some Elasticsearch is implemented as of Spring Cloud Stream Sink application: https://github.com/spring-cloud/stream-applications/tree/main/applications/sink/elasticsearch-sink." 

**Context**
I'm adding issues to the most needed extensions that don't appear in the library today.

**Comment by ipanimnim** [comment] 2022-04-09 17:01
It's also worth mentioning that ES mostly prefers bulk operations, therefore there should be native support for this.

**Comment by artembilan** [comment] 2022-04-29 14:00
Duplicate of https://github.com/spring-projects/spring-integration/issues/3527

**Closed by artembilan** 2022-04-29 14:00 UTC
Labels: type: enhancement, status: waiting-for-triage
