### ISSUE TITLE
Possible memory leak, resequencing and connection error

### ISSUE THREAD

**Issue by lkgendev** [spring-projects/spring-integration#3309] opened 2020-06-14 16:55 UTC
**Describe the bug**
When using resequencer with unbounded messages and expiration timeout, if there is an exception of `MessageHandlingException: Unable to find outbound socket in the` when sending message, the expiration is not called and the message is kept in the `groupIdToMessageGroup` and never deleted

**To Reproduce**
Create a resequencer, send a message from client to router that passes it to a server, use debugger or analyzer such as yourkit to inspect objects of the jvm, when sending the message, close the socket to the server to cause error sending from router to server, also set a timeout expiration of 1 minute and wait more than a minute

**Expected behavior**
the groupIdToMessageGroup should be empty without the message that could had error in the send connection 

**Sample**
no sample

leak code is at `processMessageForGroup`

```
				try {
					noOutput = false;
					completedMessages = completeGroup(message, correlationKey, messageGroup, lock);
				}
				finally {
					// Possible clean (implementation dependency) up
					// even if there was an exception processing messages
					afterRelease(messageGroup, completedMessages);
				}
				if (!isExpireGroupsUponCompletion() && this.minimumTimeoutForEmptyGroups > 0) {
					removeEmptyGroupAfterTimeout(messageGroup, this.minimumTimeoutForEmptyGroups);
			}
```

if `completeGroup` has exception during sending, the `removeEmptyGroupAfterTimeout` is not called

**Comment by artembilan** [comment] 2020-06-15 16:30
Well, if you have a problem on output send, it is not a correlation endpoint responsibility to remove that message message unconditionally.  The best what we can do here is to keep messages in the store to not lose them, so you can make a decision about them later on.
You should use some `try...catch` mechanism (https://docs.spring.io/spring-integration/docs/current/reference/html/messaging-endpoints.html#message-handler-advice-chain) to handle those connection errors. 
Another way is to configure a `groupTimeout` for your resequencer. This way all the unreleased messages will try to go on scheduled task. Kinda retry: https://docs.spring.io/spring-integration/docs/current/reference/html/message-routing.html#agg-and-group-to

Please, let us know what do you think?

Thanks

**Comment by lkgendev** [comment] 2020-06-18 07:52
about the groupTimeout, we are using it, and that is where the bug might be, when using groupTimeout, the function processMessageForGroup is implementing the timeout at
"
```
				if (!isExpireGroupsUponCompletion() && this.minimumTimeoutForEmptyGroups > 0) {
					removeEmptyGroupAfterTimeout(messageGroup, this.minimumTimeoutForEmptyGroups);
				}

```"
but if there is exception in
`completedMessages = completeGroup(message, correlationKey, messageGroup, lock);`
, this code for remove is not reached and the timeout remove does not work, no matter how long to wait

about the try catch message handler advice chain, I need to look into it, but the group timeout should work also if there was an error without try catch mechanism

**Comment by artembilan** [comment] 2020-06-18 14:59
One more time: the problem is on send to output channel, not in the correlation endpoint by itself.
Since it wasn't sent, the messages are note removed from the group, therefore group is not empty to perform that `removeEmptyGroupAfterTimeout()`.

As I said: we can't make unconditional decision to remove released messages from the group when those released messages are not sent out of this correlation endpoint.

**Comment by artembilan** [comment] 2020-06-18 17:40
Well, that's different approach, but again: the framework can't remove unsent messages unconditionally.

If you have a solution for your use-case, please, consider to close the issue as `Invalid`.

Thanks

**Comment by lkgendev** [comment] 2020-06-18 20:28
As I have a solution and there is a reason for not automatically removing messages when there is error, closing the case

**Closed** 2020-06-18 20:27 UTC
Labels: status: waiting-for-reporter, type: bug
