### ISSUE TITLE
Possible Bug in Error channel with custom executor channel

### ISSUE THREAD

**Issue by muhdkhokhar** [spring-projects/spring-integration#3148] opened 2020-01-20 19:44 UTC
Hi I have a file listener that is reading files parallel / more than one at a time
```

    package com.example.demo.flow;
    
    import lombok.extern.slf4j.Slf4j;
    import org.springframework.context.annotation.Bean;
    import org.springframework.integration.dsl.*;
    import org.springframework.integration.dsl.channel.MessageChannels;
    import org.springframework.integration.file.dsl.Files;
    import org.springframework.stereotype.Component;
    
    import java.io.File;
    import java.util.concurrent.Executors;
    
    /**
     * Created by muhdk on 03/01/2020.
     */
    @Component
    @Slf4j
    public class TestFlow {
    
        @Bean
        public StandardIntegrationFlow errorChannelHandler() {
    
            return IntegrationFlows.from("testChannel")
                    .handle(o -> {
    
                        log.info("Handling error....{}", o);
                    }).get();
        }
    
        @Bean
        public IntegrationFlow testFile() {
    
    
            IntegrationFlowBuilder testChannel = IntegrationFlows.from(Files.inboundAdapter(new File("d:/input-files/")),
                    e -> e.poller(Pollers.fixedDelay(5000L).maxMessagesPerPoll(5)
                            .errorChannel("testChannel")))
                    .channel(MessageChannels.executor(Executors.newFixedThreadPool(5)))
                    .transform(o -> {
    
                        throw new RuntimeException("Failing on purpose");
    
                    }).handle(o -> {
                    });
    
            return testChannel.get();
    
    
        }
    
    
    }
```

Its not going to my custom error channel 

but if I remove the line

`                .channel(MessageChannels.executor(Executors.newFixedThreadPool(5)))`

Then it goes to error channel.

How can I make it work so that it does go to my custom error channel with executor.

This is posted on https://stackoverflow.com/questions/59812326/spring-integration-dsl-custom-error-channel-issue-with-executor

**Comment by m-hofmann** [comment] 2020-01-21 14:11
I've got the same problem - errors in `transform()` are not propagated to my error channel. To me it seems the problem might have been introduced in #2986 . 

If I understand the pr correctly, there might be a regression in `LambdaMessageProcessor`: Previously, a `MessageHandlingException` was used for exceptions thrown in lambdas. Now every exception thrown in a lambda (which is always an `InvocationTargetException` due to how `Method.invoke()` works) is wrapped in an `IllegalStateException`.  Apparently the change causes all exceptions in lambdas to be interpreted as errors in your integration flow definition instead of the runtime exceptions they are.

**Comment by muhdkhokhar** [comment] 2020-01-21 14:20
I found solution myself. Looks like when using executor service you have to use differently

see my repsonse 

https://stackoverflow.com/questions/59812326/spring-integration-dsl-custom-error-channel-issue-with-executor/59843126

**Comment by artembilan** [comment] 2020-01-21 15:02
Closed in favor of mentioned StackOverflow question.
There is no confirmed bug.

Thanks

**Closed by artembilan** 2020-01-21 15:02 UTC
Labels: Invalid
