### ISSUE TITLE
Can  spring-integration provide renewable distributed locks in the future? 

### ISSUE THREAD

**Issue by maozhen520** [spring-projects/spring-integration#3636] opened 2021-09-23 09:40 UTC
This is not a bug: 

Can  spring-integration  provide renewable distributed locks in the future? Similar to redisson, it can renew the expiration time of the lock. I know that although I can directly use redisson as a redis client, our project has already used spring-integration, It is good, but we need to use renewable distributed locks, so ask, will spring-integration support renewable lock-related operations later, or why not , I am curious about your ideas

**Comment by artembilan** [comment] 2021-09-23 14:15
Starting with version `5.4` the `JdbcLockRegistry` already implements such a `RenewableLockRegistry`: https://docs.spring.io/spring-integration/docs/current/reference/html/jdbc.html#jdbc-lock-registry.

You request is really valid and if we can come up with some contract for specific `LockRegistry` we can add this hook over there. Like you brought `RedisLockRegistry` for example. 
I mean we are planning to do all of this, but on demand and when resources permit. 
The contribution is welcome: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc !

Plus we can treat this as a duplicate of this one and close respectively: https://github.com/spring-projects/spring-integration/issues/3272

**Closed by artembilan** 2021-09-23 14:15 UTC
Labels: type: enhancement, status: waiting-for-triage
