### ISSUE TITLE
MQTT issue when upgrading Paho Client

### ISSUE THREAD

**Issue by ssozonoff** [spring-projects/spring-integration#2299] opened 2017-12-04 15:17 UTC
Hello All,

We need to upgrade the version of Paho MQTT client to 1.2.0 in order to be able to tune the "MaxInFlight" parameter. However when doing this our app crashes at runtime with a Stackoverflow when instantiating the Paho Client. Has anyone else experienced this ?

Thanks

**Comment by garyrussell** [comment] 2017-12-04 16:49
Please provide more details - e.g. your configuration and the steps to reproduce as well as any logs/stack traces etc.

**Comment by artembilan** [comment] 2017-12-04 16:50
Spring Integration is based on Paho client `1.2.0` since `5.0 RC1` (https://github.com/spring-projects/spring-integration/commit/cfc698447ee37498666754e15b4de34b2a81fa04). And all our tests work well. 

Yes, please, follow Gary's requests.

**Comment by ssozonoff** [comment] 2017-12-04 17:26
Hi,

We are currently running Spring Integration version 4.3.11.RELEASE.

If you simply exclude the Paho Client dependency and bring in version 1.2.0 manually and instantiate a channel using MQTT you will get the error.

`org.springframework.context.ApplicationContextException: Failed to start bean 'mqttInbound'; nested exception is java.lang.StackOverflowError
    at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)`

Thanks

**Comment by artembilan** [comment] 2017-12-04 18:37
The Spring Integration `5.0` has been released last week: https://spring.io/blog/2017/11/29/spring-integration-5-0-ga-available

I have just tried our `4.3.x` branch with Paho `1.2.0` and works well.

> If you simply exclude the Paho Client dependency 

I wonder from where?
Please, really provide something to reproduce and full StackTrace.

**Comment by artembilan** [comment] 2018-01-23 17:44
Closed as `Works as Designed` with the leak of feedback from the reporter.

**Closed by artembilan** 2018-01-23 17:44 UTC
Labels: waiting-for-reporter
