### ISSUE TITLE
no beanFactory - set beanFactory required to false

### ISSUE THREAD

**Issue by mdrcic01** [spring-projects/spring-integration#9555] opened 2024-10-14 11:30 UTC
https://github.com/spring-projects/spring-integration/blob/c9773cda70e3d723618330295c344986f3455ab3/spring-integration-core/src/main/java/org/springframework/integration/util/AbstractExpressionEvaluator.java#L107

Hi, I see that in getEvaluationContext(boolean beanFactoryRequired) beanFactoryRequired can be set as false
I am getting a no beanFactory WARN log because i am instantiating SftpRemoteFileTemplate without a bean since i need to use DelegatingSessionFactory because of multiple hosts that need to be served
this was done according to official documentation for spring-integration and i'm still getting the WARN log

I would now like to override the said method to be called with "false" parameter so that the beanFactory is not required but this is not possible since getBeanFactory method is protected and it is being called from RemoteFileTemplate so there is no way for me to override this method

Can this be done or can you implement the solution for this problem

The warn is emerging on send(message) when it tries to call evaluateContext for remote directory

I am invoking the method from ExpressionEvaluatingMessageProcessor and hence can't override it
below is the picture of the exception

![image](https://github.com/user-attachments/assets/e54699f3-d97d-44fe-a96f-e3f9f1219398)

and this is Stack trace
`2024-10-14T14:46:50.616+02:00  WARN 1104934 --- [ool-10-thread-1] o.s.i.expression.ExpressionUtils         : Creating EvaluationContext with no beanFactory

java.lang.RuntimeException: No beanFactory
	at org.springframework.integration.expression.ExpressionUtils.createStandardEvaluationContext(ExpressionUtils.java:90) ~[spring-integration-core-6.2.1.jar:6.2.1]
	at org.springframework.integration.util.AbstractExpressionEvaluator.getEvaluationContext(AbstractExpressionEvaluator.java:111) ~[spring-integration-core-6.2.1.jar:6.2.1]
	at org.springframework.integration.util.AbstractExpressionEvaluator.getEvaluationContext(AbstractExpressionEvaluator.java:97) ~[spring-integration-core-6.2.1.jar:6.2.1]
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:169) ~[spring-integration-core-6.2.1.jar:6.2.1]
	at org.springframework.integration.util.AbstractExpressionEvaluator.evaluateExpression(AbstractExpressionEvaluator.java:127) ~[spring-integration-core-6.2.1.jar:6.2.1]
	at org.springframework.integration.handler.ExpressionEvaluatingMessageProcessor.processMessage(ExpressionEvaluatingMessageProcessor.java:109) ~[spring-integration-core-6.2.1.jar:6.2.1]
	at org.springframework.integration.file.remote.RemoteFileTemplate.doSend(RemoteFileTemplate.java:338) ~[spring-integration-file-6.2.1.jar:6.2.1]
	at org.springframework.integration.file.remote.RemoteFileTemplate.lambda$send$0(RemoteFileTemplate.java:314) ~[spring-integration-file-6.2.1.jar:6.2.1]
	at org.springframework.integration.file.remote.RemoteFileTemplate.execute(RemoteFileTemplate.java:452) ~[spring-integration-file-6.2.1.jar:6.2.1]
	at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:314) ~[spring-integration-file-6.2.1.jar:6.2.1]
	at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:302) ~[spring-integration-file-6.2.1.jar:6.2.1]
	at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:294) ~[spring-integration-file-6.2.1.jar:6.2.1]
	at com.infobip.filedistribution.datapublisher.DataTransferService.transfer(DataTransferService.java:44) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) ~[spring-aop-6.1.3.jar:6.1.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.3.jar:6.1.3]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.3.jar:6.1.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.3.jar:6.1.3]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:102) ~[spring-retry-2.0.5.jar:na]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:335) ~[spring-retry-2.0.5.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:227) ~[spring-retry-2.0.5.jar:na]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:124) ~[spring-retry-2.0.5.jar:na]
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:161) ~[spring-retry-2.0.5.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.3.jar:6.1.3]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.3.jar:6.1.3]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.3.jar:6.1.3]
	at com.infobip.filedistribution.datapublisher.DataTransferService$$SpringCGLIB$$0.transfer(<generated>) ~[classes/:na]
	at com.infobip.filedistribution.datapublisher.DataPublisher$DataPublisherTask.call(DataPublisher.java:71) ~[classes/:na]
	at com.infobip.filedistribution.datapublisher.DataPublisher$DataPublisherTask.call(DataPublisher.java:57) ~[classes/:na]`

**Comment by artembilan** [comment] 2024-10-14 13:01
Can you elaborate, please, why you cannot have that `SftpRemoteFileTemplate`  as a bean?
Does not look like a `DelegatingSessionFactory` affects somehow a decision...

**Comment by mdrcic01** [comment] 2024-10-15 08:01
I have multiple hosts that need to get different files and if i create SftpRemoteFileTemplate as a bean i need to give it whole DelegatingSessioniFactory which has all 5 hosts defined there - which will send all files to all hosts
Another option is to make 5 different beans that will not work because then it is not scallable

**Comment by artembilan** [comment] 2024-10-15 13:35
OK. I think you still create an `SftpRemoteFileTemplate` somewhere from Spring bean, so consider to implement a `BeanFactoryAware` over there and inject that `BeanFactory` to your `SftpRemoteFileTemplate`.

Another way is to look into dynamic `IntegrationFlow` where not only this bean can be created on the fly, but the whole integration solution: https://docs.spring.io/spring-integration/reference/dsl/java-runtime-flows.html

**Comment by mdrcic01** [comment] 2024-10-16 05:27
I tired to implement this, but it does not work in my context

I am creating bean of `DelegatingSessionFactory<SftpClient.DirEntry>` and using a LinkedHashMap for each of 5 different configs of type `DefaultSftpSessionFactory` providing all five of them in constructor `new DelegatingSessionFactory<>(factories, factories.values().iterator().next());`
with factories being this HashMap with all five configs

then dynamically in code i create sftpRFTemplate using factory locator - `new SftpRemoteFileTemplate(sessionFactory.getFactoryLocator().getSessionFactory(externalServiceName));`

It is working perfectly, exactly as i want it but problem is that im getting this no beanFactory exception every time service invokes `template.send();`

For that reason it would greatly help if we had a way to set the factory to notRequired

**Comment by artembilan** [comment] 2024-10-16 13:36
Right, so at the place where you do `new SftpRemoteFileTemplate()` consider to inject a `BeanFactory` which can be supplied from the Spring context by the `BeanFactoryAware` hook.

**Comment by mdrcic01** [comment] 2024-10-17 06:10
can you give me code example with SftpRemoteFileTemplate, because anything i refactor i'm getting the same error and just going in circles

**Comment by artembilan** [comment] 2024-10-17 14:31
so, let's imaging you have a service like this:
```
@Service
public class MyService implements BeanFactoryAware {

	private final DelegatingSessionFactory<SftpClient.DirEntry> sessionFactory;

	private BeanFactory beanFactory;

	public MyService(DelegatingSessionFactory<SftpClient.DirEntry> sessionFactory) {
		this.sessionFactory = sessionFactory;
	}

	@Override
	public void setBeanFactory(BeanFactory beanFactory) throws BeansException {
		this.beanFactory = beanFactory;
	}

	public void performLogic(String externalServiceName) {
		SftpRemoteFileTemplate sftpRemoteFileTemplate = 
				new SftpRemoteFileTemplate(sessionFactory.getFactoryLocator().getSessionFactory(externalServiceName));
		sftpRemoteFileTemplate.setBeanFactory(this.beanFactory);
		sftpRemoteFileTemplate.afterPropertiesSet();
	}

}
```

However it look like you abuse a `DelegatingSessionFactory` and don't use its hole power.
See, its `setThreadKey()`, which looks like exactly what is your `externalServiceName` .
So, you still can have singleton `SftpRemoteFileTemplate` bean based on just this `DelegatingSessionFactory` and then you think about calling those `setThreadKey()` and `clearThreadKey()` before and after you interact with the `SftpRemoteFileTemplate`.
Spring Integration also has a convenient `ContextHolderRequestHandlerAdvice` to let us avoid calling those methods manually.
See more info in docs: https://docs.spring.io/spring-integration/reference/handler-advice/context-holder.html.

I'm closing this issue since everything is `Work as Designed`.

**Closed by artembilan** 2024-10-17 14:31 UTC
Labels: status: waiting-for-reporter
