### ISSUE TITLE
NPE while LoggingHandler usage after changes in 4.3.4

### ISSUE THREAD

**Issue by englishman** [spring-projects/spring-integration#1936] opened 2016-10-19 19:25 UTC
The behavior of `org.springframework.integration.handler.LoggingHandler` was changed. It's possible now to create `LoggingHandler` instance with `null` in `expression` field which brings to NPE in our code after upgrade SI Java DSL from 1.1.2 (with dependency to SI core 4.2.4) to 1.2.0 (with dependency 4.3.4):

```
Caused by: java.lang.NullPointerException
	at org.springframework.integration.handler.LoggingHandler.createLogMessage(LoggingHandler.java:214)
	at org.springframework.integration.handler.LoggingHandler.handleMessageInternal(LoggingHandler.java:184)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
```

The source of the problem is this change
https://github.com/spring-projects/spring-integration/commit/c0b19e61b552c93a78a854c3be566548b0c5c3ee#diff-ffddede5f09fed28446d3aabd7150160
in `LoggingHandler` ctor. These lines were removed for some reason
```
this.evaluationContext = ExpressionUtils.createStandardEvaluationContext();
this.expression = EXPRESSION_PARSER.parseExpression("payload");
```
P.S. I can prepare PR to fix this bug

**Comment by artembilan** [comment] 2016-10-19 19:38
Hello, @englishman !

Well, there is no bug. See the `LoggingHandler.onInit()`:
```
this.evaluationContext = ExpressionUtils.createStandardEvaluationContext(getBeanFactory());
if (this.expression == null) {
	this.expression = EXPRESSION_PARSER.parseExpression("payload");
}
```
it is called by Dependency Injection container, by Spring during bean initialization phase.

Only the problem in your case that you don't populated a `LoggingHandler` instance as a bean.

What is your use-case ? 
Why it is there, but isn't a bean ?
In other words: show, please, the code to reproduce.

The problem is somewhere in the user of that class.
Thanks

**Comment by englishman** [comment] 2016-10-19 19:48
Yes, you are right we have such code in some standalone (not our team code) code:
```
public class ExceptionLoggerHandler implements ExceptionHandler {
    @Override
    public void handle(BaseXXXException e, ExceptionMetaData exceptionMetaData) {
        LoggingHandler loggingHandler = new LoggingHandler("ERROR");     // here is LoggingHandler creation as not bean
        loggingHandler.setLoggerName(getLoggerName(e, exceptionMetaData));
        String errorMessage ="";

        try {
            errorMessage = String.format(exceptionMetaData.getMessage(), (Object[]) e.getParams());
        }
        catch(Exception formatException){
            errorMessage = exceptionMetaData.getMessage() + " with params " + e.getParams();
        }

        loggingHandler.handleMessage(new GenericMessage<String>(errorMessage));
        e.printStackTrace();
    }
```

**Comment by artembilan** [comment] 2016-10-19 19:56
Good.
Can fix that with the `setBeanFactory()` and `afterPropertiesSet()` calls?

We can add an `Assert.notNull(this.expression)` to the `LoggingHandler.handleMessageInternal()`, but that won't help you to overcome the limitation.

On the other hand that looks odd to use messaging component just for logging...
That `ExceptionLoggerHandler` has a bad design. I agree that `LoggingHandler` has some tips with that SpEL power, but that does not make sense since in this code you always have the same `new GenericMessage<String>(errorMessage)` style.

I can't insist, but I'd drop this code at all and would do something myself:
1. That code use wrong approach
2. It has an overhead with redundant `new GenericMessage()`
3. It `printStackTrace();` unconditionally!

**Comment by englishman** [comment] 2016-10-19 20:11
The question now isn't about about `ExceptionLoggerHandler` design. Personally, I agree with you but: 

1. Is this good to change behavior of some SI components this (let's say, Linux core) way? I don't know what agreement do you have in Spring team for this in general. Is this acceptable or you have to keep the same behavior (Windows OS backward compatibility way)?
2. If it's acceptable then don't allow to use `LoggingHandler` in the wrong way (add some assertions, make ctors not public etc.).
3. Personally, I don't like `LoggingHandler` design at all: it allows to create `LoggingHandler` instance in inconsistent state (isn't ready to work). Why don't simply define `expression` field like this
```
private volatile Expression expression = EXPRESSION_PARSER.parseExpression("payload");
```
? I can't see any reason to do kind of 'optimization' of `expression` initialization later in `onInit()` method.

**Comment by garyrussell** [comment] 2016-10-19 20:36
We generally try to avoid breaking changes and provide backwards compatibility whenever possible.

Certainly, NPEs are verboten and this should at least be protected against here and we should be able to fall-back to the old behavior if the bean was not initialized by the application context.

**Comment by artembilan** [comment] 2016-10-19 20:36
1. Right, in general we try to follow with the backward compatibility. But as we see by the end code, it is just a cause of wrong usage. 
2. Well, we can't do that because there is always a convenient way to create beans via `@Bean` and `new` operator. Visually it is the same code as your current usage, but with the difference that `@Bean` will be involved in the initialization phase. Transparently for you. 
3. That is your opinion. But don't forget that you use Spring, which in many cases requires some environment and container initialization for components. Otherwise, yes: they are in the inconsistent state.
We can't always protect ourselves from silly usage of our components. 

That reminds me as one guy (Baruch Sadogursky ?) talked about their Aritfactory plugins model. And how it started to limit code access via some cool Groovy reflection tool. Finally he decided that it doesn't worth. So much time to waste for protection end-users from their own foolishness.

As I said: we can add an assertion, but that doesn't help you. Even if we reinstate the old behavior of this component, that doesn't mean that you stop to use this API wrong way.

ALL Spring Integration component must be beans and their instances can be used only via DI.

**Comment by artembilan** [comment] 2016-10-19 21:32
BTW, @englishman , 

Since we are all here agree that there is need some fix for the `LoggingHandler`, feel free to raise some PR on the matter.

Regarding backward compatibility and consistent state we can continue discussion already on the change.

And who knows: maybe eventually we will come up with the practice to provide consistent protection everywhere...

Thank you for your valuable discussion, as always! :smile:

**Comment by englishman** [comment] 2016-10-19 22:08
1. I've rewritten crappy `ExceptionLoggerHandler`, found the way to inject the new version into standalone lib and, thus, get rid of SI `LoggingHandler` usage at all. So, basically, no more problems :smile: 
2. as for PR... Could you, pls, explain why have you moved `evaluationContext` and `expression` initialization into `onInit` method? Your answer will give me more understating what I can improve here (and how).

**Comment by artembilan** [comment] 2016-10-20 01:14
Great!

The `evaluationContext` must be supplied with `BeanFactory`. We can get that one only after `setBeanFactory()`, which is called by the Spring context. 
I might agree that `expression` could be initialized during instantiating, but not `evaluationContext`. There are can be other options which require the Spring context involvement, e.g. `globalProperties` etc.
That's why we can initialize those options only in the `afterPropertiesSet()`. And that's why I don't see reason to fight for the standalone usage of the `LoggingHandler`, as well as any other out-of-the-box SI components. More over `LoggingHandler` is for `Message<?>` handling from the wrapping Consumer and so on. Really, does not make sense to use this component as a standalone. Even if its design isn't ideal, it works in most appropriate scenarios. But, eh, we have to prevent that NPE, agreed. :smile:

**Comment by artembilan** [comment] 2016-10-20 14:23
See JIRA on the matter: https://jira.spring.io/browse/INT-4144
Contribution recommendations are here: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc

**Comment by englishman** [comment] 2016-10-20 16:12
@artembilan :+1:

**Comment by englishman** [comment] 2016-10-21 22:31
@artembilan created #1940 PR

**Closed** 2016-10-25 14:53 UTC
