### ISSUE TITLE
Delayer with JdbcMessageStore does not release messages

### ISSUE THREAD

**Issue by sbaby83** [spring-projects/spring-integration#8773] opened 2023-10-24 08:31 UTC
Since 6.1.3 and the commit https://github.com/spring-projects/spring-integration/pull/8733/commits/032df6204ff801493ffaabafe8312eafdd5860c5

The message is not released by delayer and this text appears in logs :

> "No message in the Message Store to release: " + message +
> 					". Likely another instance has already released it."

**To Reproduce**

> IntegrationFlow
      .from("firstTryChannel")
      .delay(
        "firstTry",
        d ->  d.defaultDelay(firstTryDelay)
            .transactionalRelease(transactionInterceptorAdvice)
            .maxAttempts(1)
            .messageStore(jdbcMessageStore)
            .delayedMessageErrorChannel("secondTryChannel")
      )
      .channel(FLOW_INPUT_CHANNEL)
      .get();

**Expected behavior**

The message is released by delayer.

**Comment by artembilan** [comment] 2023-10-24 15:31
Confirmed.
We have a logic in the `DelayHandler` like `return ((MessageStore) this.messageStore).removeMessage(message.getHeaders().getId()) != null;` where it fails now because we check if message is not in any group any more.

Unfortunately our `DelayerHandlerRescheduleIntegrationTests` is marked as `@LongRunningTest` and it is missed from any test suites 😢

**Closed** 2023-11-03 19:09 UTC
Labels: type: bug, in: core, backport 6.1.x
