### ISSUE TITLE
Issues in Sping integration mail idle receiver

### ISSUE THREAD

**Issue by angeloimm** [spring-projects/spring-integration#3257] opened 2020-04-23 09:11 UTC
**Framework version**

- Spring boot 2.2.6.RELEASE
- Spring Integration Mail

**Bug description**
I'm using IMAP server and idle configuration
I wrote the following code:

```
@Autowired
private IntegrationFlowContext flowContext;
IntegrationFlow flow = null;
String userFlag = confMailIn.getHost() + "_idle_adapter";
ImapIdleChannelAdapterSpec imapIdleChannelAdapterSpec = Mail.imapIdleAdapter(connectionUrl.toString())
        .javaMailProperties(javaMailProperties)
        .shouldDeleteMessages(deleteMessages)
        .shouldMarkMessagesAsRead(markMessagesRead)
        .autoStartup(true)
        .autoCloseFolder(false)
        .userFlag(userFlag)
        .id(userFlag)
        //.searchTermStrategy(this::notSeenTerm)
        .selector(selectFunction);

if (confMailIn.isRichiedeAutenticazione()) {
    imapIdleChannelAdapterSpec = imapIdleChannelAdapterSpec.javaMailAuthenticator(new CasellaPostaleAuthenticator(cpd.getIndirizzoMail(), cpd.getUsername(), cpd.getPassword()));
}
flow = IntegrationFlows
        .from(imapIdleChannelAdapterSpec)
        .handle(message ->{
            //Prendo il closable del messaggio e valorizzo i l'elenco di closeale da chiudere
            Closeable closeable = StaticMessageHeaderAccessor.getCloseableResource(message);
            if( !closeables.containsKey(cpd.getIndirizzoMail()) ) {
                closeables.put(cpd.getIndirizzoMail(), closeable);
            }
            publishMailEvent(message);
        })
        .get();
flowContext.registration(flow).id(flowId).register();
```
I set to false the auto close folder because if it's true I can't handle the mail message because I receive a `FolderClosedException`. So I collect all the `Closeable` objects and I close them when Spring context is closed (in the best scenario.... never :) )

So far so good... I register the flow and it starts working. But I noticed that after some time it stops in receiving mail messages. I need to restart my service and once again it works for some time.

When it works I see these logs:
```
2020-04-20 16:32:57,427 25199841 [scheduling-1] DEBUG o.s.i.mail.ImapIdleChannelAdapter - waiting for mail 
2020-04-20 16:32:57,460 25199874 [scheduling-1] INFO  o.s.i.mail.ImapMailReceiver - attempting to receive mail from folder [INBOX] 
2020-04-20 16:32:57,460 25199874 [scheduling-1] DEBUG o.s.i.mail.ImapMailReceiver - This email server does not support RECENT flag, but it does support USER flags which will be used to prevent duplicates during email fetch. This receiver instance uses flag: imapmail.libero.it_idle_adapter 
2020-04-20 16:32:57,476 25199890 [scheduling-1] DEBUG o.s.i.mail.ImapMailReceiver - found 0 new messages 
2020-04-20 16:32:57,476 25199890 [scheduling-1] DEBUG o.s.i.mail.ImapMailReceiver - Received 0 messages 
2020-04-20 16:32:57,476 25199890 [scheduling-1] DEBUG o.s.i.mail.ImapIdleChannelAdapter - received 0 mail messages 
2020-04-20 16:32:57,476 25199890 [scheduling-1] DEBUG o.s.i.mail.ImapIdleChannelAdapter - Task completed successfully. Re-scheduling it again right away.
```

All works pretty good If I set auto close folder true in my code like in this way

```
@Autowired
private IntegrationFlowContext flowContext;
IntegrationFlow flow = null;
String userFlag = confMailIn.getHost() + "_idle_adapter";
ImapIdleChannelAdapterSpec imapIdleChannelAdapterSpec = Mail.imapIdleAdapter(connectionUrl.toString())
        .javaMailProperties(javaMailProperties)
        .shouldDeleteMessages(deleteMessages)
        .shouldMarkMessagesAsRead(markMessagesRead)
        .autoStartup(true)
        .autoCloseFolder(true)
        .userFlag(userFlag)
        .id(userFlag)
        //.searchTermStrategy(this::notSeenTerm)
        .selector(selectFunction);

if (confMailIn.isRichiedeAutenticazione()) {
    imapIdleChannelAdapterSpec = imapIdleChannelAdapterSpec.javaMailAuthenticator(new CasellaPostaleAuthenticator(cpd.getIndirizzoMail(), cpd.getUsername(), cpd.getPassword()));
}
flow = IntegrationFlows
        .from(imapIdleChannelAdapterSpec)
        .handle(message ->{
System.out.println("Mail received");
        })
        .get();
flowContext.registration(flow).id(flowId).register();
```

**Comment by artembilan** [comment] 2020-04-23 14:07
Related SO thread: https://stackoverflow.com/questions/61359499/issues-in-sping-integration-mail-idle-receiver

**Comment by artembilan** [comment] 2020-04-23 18:18
Well, not sure what is going on in your case works well for me with this configuration against GMail:

```
@Bean
	IntegrationFlow imapFlow() {
		return IntegrationFlows
				.from(Mail.imapIdleAdapter(this.imapUrl)
						.javaMailProperties(propertiesBuilder -> propertiesBuilder
								.put("mail.imap.socketFactory.class", javax.net.ssl.SSLSocketFactory.class)
								.put("mail.imap.socketFactory.fallback", false)
								.put("mail.store.protocol", "imaps")
								.put("mail.debug", true))
						.autoCloseFolder(false))
				.handle(message -> System.out.println("Mail received: " + message))
				.get();
	}
```

```
2020-04-23 14:03:19.617  INFO 12460 --- [           main] o.s.i.mail.ImapIdleChannelAdapter        : started bean 'imapFlow.mail:imap-idle-channel-adapter#0'; defined in: 'org.springframework.integration.sample.imap.ImapIdleSampleApplication'; from source: 'bean method imapFlow'
2020-04-23 14:03:19.618 DEBUG 12460 --- [ask-scheduler-1] o.s.i.mail.ImapIdleChannelAdapter        : waiting for mail
2020-04-23 14:03:19.624  INFO 12460 --- [           main] o.s.i.s.imap.ImapIdleSampleApplication   : Started ImapIdleSampleApplication in 0.93 seconds (JVM running for 1.525)
2020-04-23 14:03:19.624 DEBUG 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : connecting to store [imaps://clericsmail@imap.gmail.com]
2020-04-23 14:03:20.591 DEBUG 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : opening folder [imaps://clericsmail@imap.gmail.com/INBOX]
2020-04-23 14:03:20.691 DEBUG 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : This email server does not support RECENT flag, but it does support USER flags which will be used to prevent duplicates during email fetch. This receiver instance uses flag: spring-integration-mail-adapter
2020-04-23 14:03:51.162  INFO 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : attempting to receive mail from folder [INBOX]
2020-04-23 14:03:51.163 DEBUG 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : This email server does not support RECENT flag, but it does support USER flags which will be used to prevent duplicates during email fetch. This receiver instance uses flag: spring-integration-mail-adapter
2020-04-23 14:03:51.279 DEBUG 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : found 1 new messages
2020-04-23 14:03:51.386 DEBUG 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : Received 1 messages
2020-04-23 14:03:51.387 DEBUG 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : USER flags are supported by this mail server. Flagging message with 'spring-integration-mail-adapter' user flag
2020-04-23 14:03:51.996 DEBUG 12460 --- [ask-scheduler-1] o.s.i.mail.ImapIdleChannelAdapter        : received 1 mail messages
2020-04-23 14:03:51.996 DEBUG 12460 --- [ask-scheduler-1] o.s.i.mail.ImapIdleChannelAdapter        : Task completed successfully. Re-scheduling it again right away.
2020-04-23 14:03:51.997 DEBUG 12460 --- [ask-scheduler-2] o.s.i.mail.ImapIdleChannelAdapter        : waiting for mail
2020-04-23 14:03:51.997 DEBUG 12460 --- [pool-1-thread-1] o.s.integration.channel.DirectChannel    : preSend on channel 'bean 'imapFlow.channel#0'; defined in: 'org.springframework.integration.sample.imap.ImapIdleSampleApplication'; from source: 'bean method imapFlow'', message: GenericMessage [payload=org.springframework.integration.mail.AbstractMailReceiver$IntegrationMimeMessage@5c94e66, headers={closeableResource=org.springframework.integration.mail.AbstractMailReceiver$$Lambda$265/1288790922@40cbc0bb, id=6b30ce22-86a9-9e28-2b92-e5e62945e73b, timestamp=1587665031996}]
Mail received: GenericMessage [payload=org.springframework.integration.mail.AbstractMailReceiver$IntegrationMimeMessage@5c94e66, headers={closeableResource=org.springframework.integration.mail.AbstractMailReceiver$$Lambda$265/1288790922@40cbc0bb, id=6b30ce22-86a9-9e28-2b92-e5e62945e73b, timestamp=1587665031996}]
2020-04-23 14:03:51.998 DEBUG 12460 --- [pool-1-thread-1] o.s.integration.channel.DirectChannel    : postSend (sent=true) on channel 'bean 'imapFlow.channel#0'; defined in: 'org.springframework.integration.sample.imap.ImapIdleSampleApplication'; from source: 'bean method imapFlow'', message: GenericMessage [payload=org.springframework.integration.mail.AbstractMailReceiver$IntegrationMimeMessage@5c94e66, headers={closeableResource=org.springframework.integration.mail.AbstractMailReceiver$$Lambda$265/1288790922@40cbc0bb, id=6b30ce22-86a9-9e28-2b92-e5e62945e73b, timestamp=1587665031996}]
2020-04-23 14:03:52.659 DEBUG 12460 --- [ask-scheduler-2] o.s.integration.mail.ImapMailReceiver    : This email server does not support RECENT flag, but it does support USER flags which will be used to prevent duplicates during email fetch. This receiver instance uses flag: spring-integration-mail-adapter
2020-04-23 14:04:18.096  INFO 12460 --- [ask-scheduler-2] o.s.integration.mail.ImapMailReceiver    : attempting to receive mail from folder [INBOX]
2020-04-23 14:04:18.096 DEBUG 12460 --- [ask-scheduler-2] o.s.integration.mail.ImapMailReceiver    : This email server does not support RECENT flag, but it does support USER flags which will be used to prevent duplicates during email fetch. This receiver instance uses flag: spring-integration-mail-adapter
2020-04-23 14:04:18.215 DEBUG 12460 --- [ask-scheduler-2] o.s.integration.mail.ImapMailReceiver    : found 1 new messages
2020-04-23 14:04:18.378 DEBUG 12460 --- [ask-scheduler-2] o.s.integration.mail.ImapMailReceiver    : Received 1 messages
2020-04-23 14:04:18.378 DEBUG 12460 --- [ask-scheduler-2] o.s.integration.mail.ImapMailReceiver    : USER flags are supported by this mail server. Flagging message with 'spring-integration-mail-adapter' user flag
2020-04-23 14:04:18.966 DEBUG 12460 --- [ask-scheduler-2] o.s.i.mail.ImapIdleChannelAdapter        : received 1 mail messages
2020-04-23 14:04:18.967 DEBUG 12460 --- [ask-scheduler-2] o.s.i.mail.ImapIdleChannelAdapter        : Task completed successfully. Re-scheduling it again right away.
2020-04-23 14:04:18.967 DEBUG 12460 --- [pool-1-thread-1] o.s.integration.channel.DirectChannel    : preSend on channel 'bean 'imapFlow.channel#0'; defined in: 'org.springframework.integration.sample.imap.ImapIdleSampleApplication'; from source: 'bean method imapFlow'', message: GenericMessage [payload=org.springframework.integration.mail.AbstractMailReceiver$IntegrationMimeMessage@44f59285, headers={closeableResource=org.springframework.integration.mail.AbstractMailReceiver$$Lambda$265/1288790922@3ce9d206, id=9a766a47-7faa-c489-987a-73ae5ad9cdfa, timestamp=1587665058966}]
Mail received: GenericMessage [payload=org.springframework.integration.mail.AbstractMailReceiver$IntegrationMimeMessage@44f59285, headers={closeableResource=org.springframework.integration.mail.AbstractMailReceiver$$Lambda$265/1288790922@3ce9d206, id=9a766a47-7faa-c489-987a-73ae5ad9cdfa, timestamp=1587665058966}]
2020-04-23 14:04:18.967 DEBUG 12460 --- [pool-1-thread-1] o.s.integration.channel.DirectChannel    : postSend (sent=true) on channel 'bean 'imapFlow.channel#0'; defined in: 'org.springframework.integration.sample.imap.ImapIdleSampleApplication'; from source: 'bean method imapFlow'', message: GenericMessage [payload=org.springframework.integration.mail.AbstractMailReceiver$IntegrationMimeMessage@44f59285, headers={closeableResource=org.springframework.integration.mail.AbstractMailReceiver$$Lambda$265/1288790922@3ce9d206, id=9a766a47-7faa-c489-987a-73ae5ad9cdfa, timestamp=1587665058966}]
2020-04-23 14:04:18.967 DEBUG 12460 --- [ask-scheduler-1] o.s.i.mail.ImapIdleChannelAdapter        : waiting for mail
2020-04-23 14:04:19.150 DEBUG 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : This email server does not support RECENT flag, but it does support USER flags which will be used to prevent duplicates during email fetch. This receiver instance uses flag: spring-integration-mail-adapter
2020-04-23 14:04:49.594  INFO 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : attempting to receive mail from folder [INBOX]
2020-04-23 14:04:49.594 DEBUG 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : This email server does not support RECENT flag, but it does support USER flags which will be used to prevent duplicates during email fetch. This receiver instance uses flag: spring-integration-mail-adapter
2020-04-23 14:04:49.713 DEBUG 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : found 1 new messages
2020-04-23 14:04:49.812 DEBUG 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : Received 1 messages
2020-04-23 14:04:49.812 DEBUG 12460 --- [ask-scheduler-1] o.s.integration.mail.ImapMailReceiver    : USER flags are supported by this mail server. Flagging message with 'spring-integration-mail-adapter' user flag
2020-04-23 14:04:50.426 DEBUG 12460 --- [ask-scheduler-1] o.s.i.mail.ImapIdleChannelAdapter        : received 1 mail messages
2020-04-23 14:04:50.426 DEBUG 12460 --- [ask-scheduler-1] o.s.i.mail.ImapIdleChannelAdapter        : Task completed successfully. Re-scheduling it again right away.
2020-04-23 14:04:50.427 DEBUG 12460 --- [pool-1-thread-1] o.s.integration.channel.DirectChannel    : preSend on channel 'bean 'imapFlow.channel#0'; defined in: 'org.springframework.integration.sample.imap.ImapIdleSampleApplication'; from source: 'bean method imapFlow'', message: GenericMessage [payload=org.springframework.integration.mail.AbstractMailReceiver$IntegrationMimeMessage@2530737c, headers={closeableResource=org.springframework.integration.mail.AbstractMailReceiver$$Lambda$265/1288790922@24aae3b1, id=3b65aad7-1fea-74bf-23e0-b25908386017, timestamp=1587665090426}]
2020-04-23 14:04:50.427 DEBUG 12460 --- [ask-scheduler-4] o.s.i.mail.ImapIdleChannelAdapter        : waiting for mail
Mail received: GenericMessage [payload=org.springframework.integration.mail.AbstractMailReceiver$IntegrationMimeMessage@2530737c, headers={closeableResource=org.springframework.integration.mail.AbstractMailReceiver$$Lambda$265/1288790922@24aae3b1, id=3b65aad7-1fea-74bf-23e0-b25908386017, timestamp=1587665090426}]
2020-04-23 14:04:50.427 DEBUG 12460 --- [pool-1-thread-1] o.s.integration.channel.DirectChannel    : postSend (sent=true) on channel 'bean 'imapFlow.channel#0'; defined in: 'org.springframework.integration.sample.imap.ImapIdleSampleApplication'; from source: 'bean method imapFlow'', message: GenericMessage [payload=org.springframework.integration.mail.AbstractMailReceiver$IntegrationMimeMessage@2530737c, headers={closeableResource=org.springframework.integration.mail.AbstractMailReceiver$$Lambda$265/1288790922@24aae3b1, id=3b65aad7-1fea-74bf-23e0-b25908386017, timestamp=1587665090426}]
2020-04-23 14:04:50.608 DEBUG 12460 --- [ask-scheduler-4] o.s.integration.mail.ImapMailReceiver    : This email server does not support RECENT flag, but it does support USER flags which will be used to prevent duplicates during email fetch. This receiver instance uses flag: spring-integration-mail-adapter

```

As you see I have only one `opening folder [imaps://clericsmail@imap.gmail.com/INBOX]` message in logs, but I can still read new arriving message into a mail box.

Maybe your `.selector(selectFunction)` is guilty somehow?..

any chances to share a minimal reproducable sample? So, I can connect it to mail GMail box and play with.

Thanks for understanding!

**Comment by angeloimm** [comment] 2020-04-24 07:04
Hi Artem. First of all thank you for the support.
I'll try to share a GitHub project this weekend.
What I do in my case is the following: I'm listening on the IMAP server. When a mail message is received I need to read it and store information in my DB and mail message attachments in Alfresco. So what do I do? I receive the message and read it and finally publish it by using `org.springframework.context.ApplicationEventPublisher` so that another thread will make DB CRUD operations and alfresco interaction.

My `.selector(selectFunction)` is the following one:
```
Function<MimeMessage, Boolean> selectFunction = (MimeMessage message) -> {
	try {
		return true;
		/*
		Date dataRicezione = message.getReceivedDate();
		DateTime today = new DateTime().withTimeAtStartOfDay();
		DateTime tomorrow = today.plusDays(1).withTimeAtStartOfDay();
		if( logger.isInfoEnabled() ) {
			logger.info("Data ricezione {} today {} tomorrow {}", dataRicezione, today, tomorrow);
		}
		return dataRicezione.after(today.toDate()) && dataRicezione.before(tomorrow.toDate());
		 */
	}catch (Exception e) {
		logger.error("Errore nel recupero del messaggio in selectFunction", e);
		return false;
	}
};
```
As you can see it always returns `true`

What I didn't put in my JavaMail properties, instead, is the following
```
.put("mail.imap.socketFactory.class", javax.net.ssl.SSLSocketFactory.class)
.put("mail.imap.socketFactory.fallback", false)
```

I'll try by adding them

In any case I'll share a reproducable sample this weekend.

**Comment by artembilan** [comment] 2020-04-30 16:01
Hi @angeloimm !

Any news over here?

We are in the last two weeks GA phase, so would be great to have a fix for the issue if any.

Thanks

**Comment by angeloimm** [comment] 2020-05-03 09:39
Hello @artembilan 
Sorry for being so late but I have been very busy.

I shared this project https://github.com/angeloimm/spring_integration_mail_example and I tried to reproduce the issue and I guess I have been able in reproducing it.

I started from my orignal project and I cleaned with useless things. In it you can find:

- it.olegna.spring.integration.mail.be.service.impl.IntegrationFlowManagerSvcImpl: a spring service where I configure all the mails I want to listen on

- it.olegna.spring.integration.mail.be.web.controller.CasellaPostaleController: a simple controller where users can configure their own mails

- it.olegna.spring.integration.mail.be.TestConfigurazioneCasellaPostale: a simple test class who will call the controller and user can configura mail. I put also a configurazioneCasellaPostaleTemplate.json that is a template for JSON to be sent to the controller

As you can see I configured 2 ImapIdleChannelAdapterSpec one with autoclose = false and another with autoclose = true. The second one just logs that a mail message has been received

I sent a mail message and this is my log result:
```
2020-05-03 11:35:04,416 16637 [XNIO-1 task-1] INFO  i.o.s.i.m.b.s.i.IntegrationFlowManagerSvcImpl - Avvio mail receiver per la casella di posta angelo.immediata@ordingsa.it REQUEST_PATH_ID=http://localhost:8080/casella-postale/configura-casella, microservice=webmail.be, REMOTE_HOST_ID=127.0.0.1, UUID_ID=2ddc46a3-6af2-4f14-bc0c-7324e06f452e
2020-05-03 11:35:04,416 16637 [XNIO-1 task-1] INFO  i.o.s.i.m.b.s.i.IntegrationFlowManagerSvcImpl - Avvio ImapMailReceiver REQUEST_PATH_ID=http://localhost:8080/casella-postale/configura-casella, microservice=webmail.be, REMOTE_HOST_ID=127.0.0.1, UUID_ID=2ddc46a3-6af2-4f14-bc0c-7324e06f452e
2020-05-03 11:35:04,418 16639 [XNIO-1 task-1] INFO  i.o.s.i.m.b.s.i.IntegrationFlowManagerSvcImpl - Casella postale imaps.pec.aruba.it protocollo IMAP con supporto IDLE REQUEST_PATH_ID=http://localhost:8080/casella-postale/configura-casella, microservice=webmail.be, REMOTE_HOST_ID=127.0.0.1, UUID_ID=2ddc46a3-6af2-4f14-bc0c-7324e06f452e
2020-05-03 11:35:04,459 16680 [XNIO-1 task-1] INFO  o.s.i.channel.DirectChannel - Channel 'application.RICEZIONE_MAIL_FLOW_angelo.immediata@ordingsa.it.channel#0' has 1 subscriber(s). REQUEST_PATH_ID=http://localhost:8080/casella-postale/configura-casella, microservice=webmail.be, REMOTE_HOST_ID=127.0.0.1, UUID_ID=2ddc46a3-6af2-4f14-bc0c-7324e06f452e
2020-05-03 11:35:04,459 16680 [XNIO-1 task-1] INFO  o.s.i.endpoint.EventDrivenConsumer - started bean 'RICEZIONE_MAIL_FLOW_angelo.immediata@ordingsa.it.org.springframework.integration.config.ConsumerEndpointFactoryBean#0' REQUEST_PATH_ID=http://localhost:8080/casella-postale/configura-casella, microservice=webmail.be, REMOTE_HOST_ID=127.0.0.1, UUID_ID=2ddc46a3-6af2-4f14-bc0c-7324e06f452e
2020-05-03 11:35:04,462 16683 [XNIO-1 task-1] INFO  o.s.i.mail.ImapIdleChannelAdapter - started bean 'imaps.pec.aruba.it_idle_adapter' REQUEST_PATH_ID=http://localhost:8080/casella-postale/configura-casella, microservice=webmail.be, REMOTE_HOST_ID=127.0.0.1, UUID_ID=2ddc46a3-6af2-4f14-bc0c-7324e06f452e
2020-05-03 11:35:04,467 16688 [XNIO-1 task-1] INFO  o.s.i.channel.DirectChannel - Channel 'application.RICEZIONE_MAIL_FLOW_angelo.immediata@ordingsa.itAUTOCLOSE.channel#0' has 1 subscriber(s). REQUEST_PATH_ID=http://localhost:8080/casella-postale/configura-casella, microservice=webmail.be, REMOTE_HOST_ID=127.0.0.1, UUID_ID=2ddc46a3-6af2-4f14-bc0c-7324e06f452e
2020-05-03 11:35:04,467 16688 [XNIO-1 task-1] INFO  o.s.i.endpoint.EventDrivenConsumer - started bean 'RICEZIONE_MAIL_FLOW_angelo.immediata@ordingsa.itAUTOCLOSE.org.springframework.integration.config.ConsumerEndpointFactoryBean#0' REQUEST_PATH_ID=http://localhost:8080/casella-postale/configura-casella, microservice=webmail.be, REMOTE_HOST_ID=127.0.0.1, UUID_ID=2ddc46a3-6af2-4f14-bc0c-7324e06f452e
2020-05-03 11:35:04,476 16697 [XNIO-1 task-1] INFO  o.s.i.mail.ImapIdleChannelAdapter - started bean 'imaps.pec.aruba.it_idle_adapterAUTOCLOSE' REQUEST_PATH_ID=http://localhost:8080/casella-postale/configura-casella, microservice=webmail.be, REMOTE_HOST_ID=127.0.0.1, UUID_ID=2ddc46a3-6af2-4f14-bc0c-7324e06f452e
2020-05-03 11:36:05,435 77656 [task-scheduler-1] INFO  o.s.i.mail.ImapMailReceiver - attempting to receive mail from folder [INBOX] 
2020-05-03 11:36:05,568 77789 [task-scheduler-2] INFO  o.s.i.mail.ImapMailReceiver - attempting to receive mail from folder [INBOX] 
2020-05-03 11:36:06,106 78327 [pool-4-thread-1] INFO  i.o.s.i.m.b.s.i.IntegrationFlowManagerSvcImpl - Publishing event 
2020-05-03 11:36:06,301 78522 [asyncTaskExecutor-2] INFO  i.o.s.i.m.b.h.MailMessageHandler - Got this message ACCETTAZIONE: test 1 
2020-05-03 11:36:06,303 78524 [pool-4-thread-1] INFO  i.o.s.i.m.b.s.i.IntegrationFlowManagerSvcImpl - Publishing event 
2020-05-03 11:36:06,323 78544 [pool-5-thread-1] INFO  i.o.s.i.m.b.s.i.IntegrationFlowManagerSvcImpl - Message received 
2020-05-03 11:36:06,324 78545 [pool-5-thread-1] INFO  i.o.s.i.m.b.s.i.IntegrationFlowManagerSvcImpl - Message received 
2020-05-03 11:36:06,325 78546 [pool-5-thread-1] INFO  i.o.s.i.m.b.s.i.IntegrationFlowManagerSvcImpl - Message received 
2020-05-03 11:36:06,565 78786 [pool-4-thread-1] INFO  i.o.s.i.m.b.s.i.IntegrationFlowManagerSvcImpl - Publishing event 
2020-05-03 11:36:06,565 78786 [asyncTaskExecutor-3] INFO  i.o.s.i.m.b.h.MailMessageHandler - Got this message POSTA CERTIFICATA: test 1 
2020-05-03 11:36:06,941 79162 [task-scheduler-3] INFO  o.s.i.mail.ImapMailReceiver - attempting to receive mail from folder [INBOX] 
2020-05-03 11:36:06,945 79166 [asyncTaskExecutor-9] INFO  i.o.s.i.m.b.h.MailMessageHandler - Got this message CONSEGNA: test 1 
2020-05-03 11:37:36,664 168885 [task-scheduler-4] INFO  o.s.i.mail.ImapMailReceiver - attempting to receive mail from folder [INBOX] 
2020-05-03 11:37:37,237 169458 [task-scheduler-5] INFO  o.s.i.mail.ImapMailReceiver - attempting to receive mail from folder [INBOX] 
2020-05-03 11:37:37,332 169553 [pool-5-thread-1] INFO  i.o.s.i.m.b.s.i.IntegrationFlowManagerSvcImpl - Message received 
2020-05-03 11:37:37,333 169554 [pool-5-thread-1] INFO  i.o.s.i.m.b.s.i.IntegrationFlowManagerSvcImpl - Message received 
2020-05-03 11:37:37,333 169554 [pool-5-thread-1] INFO  i.o.s.i.m.b.s.i.IntegrationFlowManagerSvcImpl - Message received 
```

I sent 2 mails with 1 simple attachment. The first time both the flows received the messages. In the second case I just saw the autoclose flow receiving the message

**Comment by artembilan** [comment] 2020-05-04 15:32
Sorry, no, you project is too complicated to understand what  is going on.

Please, consider to make it fully simple. As you said: two `ImapIdleChannelAdapterSpec`. So, probably a project just with those and simple configuration properties to let me to inject my own GMail credentials.

Thanks for understanding!

**Comment by angeloimm** [comment] 2020-05-05 12:48
Hi @artembilan 
I simplified the project. Now the only interested class is `it.olegna.spring.integration.mail.be.service.impl.IntegrationFlowManagerSvcImpl` and its method `it.olegna.spring.integration.mail.be.service.impl.IntegrationFlowManagerSvcImpl.avviaImapMailReceiver()`

In this method you can set you gmail credentials

Angelo

**Comment by artembilan** [comment] 2020-05-05 16:03
Thanks, but your project is still too big for me to grok.
You need to understand that I have to run it locally. 
Since we talk about email over here, it is really very destructive to figure out other matter in the project.

Please, make a sample project with minimal config only about email.

**Comment by artembilan** [comment] 2020-05-05 16:05
OK. I'll try to open it. Although not sure if I can run it with all those certs and SQL...

**Comment by artembilan** [comment] 2020-05-05 16:35
No, that's still to complicated.

Why do we need that custom `CasellaPostaleAuthenticator`? In my case it works without anything custom.
Do you test against GMail? I'm not sure that it allows to pull messages from a plain `imap` - I use `imaps` for testing...

I don't see that you use properties I've mentioned above:
```
.javaMailProperties(propertiesBuilder -> propertiesBuilder
								.put("mail.imap.socketFactory.class", javax.net.ssl.SSLSocketFactory.class)
								.put("mail.imap.socketFactory.fallback", false)
								.put("mail.store.protocol", "imaps")
								.put("mail.debug", true))
```

Probably you test it against not GMail, but some other email server...
You server might not allow to see new messages for already opened folders.

Sorry, I'm not so good in email protocol, so I need something really simple and obvious to play with against my GMail account.

Thanks for understanding.

**Comment by artembilan** [comment] 2020-05-05 19:53
OK. I have some further observation:
1. You can't fetch those messages from the box which are already marked as `read`. See your your configuration: `webmail.be.imap.mark.message.read=true`. 
2. Both of your IMAP channel adapters uses the same `.userFlag(userFlag)`. So, it is kinda obvious that e-mail server treats them as the same client.

In the end it looks like our non-folder-closing configuration got unlucky - all the messages are read by other channel adapter or client. 😄

**Comment by angeloimm** [comment] 2020-05-05 20:22
Ho @artembilan 
Well I adapted my original code too quickly in these two days...
In origin I have only 1 adapter (or imap idle with autoclose false or imap polling or pop3)
Sadly it’s a very intense period to me (dammed coronavirus 😂😂)but tomorrow I’ll make the project as much simple as possible
Thank you for support and please forgive me if I bothering you

**Comment by artembilan** [comment] 2020-05-05 20:24
No problem! As you see I have managed to run your project and was able to reproduce.
But then I have figured out how to fix it.
Or use `markAsRead = false` - or use only one channel adapter!

**Comment by artembilan** [comment] 2020-09-14 18:17
Closing as `Works as Designed` and as an issue in end-user configuration.
Plus there is no feedback for a while.

Feel free to reopen if you have some further justification about a bug in the framework.

Thanks for undertstanding!

**Closed by artembilan** 2020-09-14 18:17 UTC
Labels: in: mail, status: waiting-for-reporter, type: bug
