### ISSUE TITLE
MessagingGateway's temporary reply channel does not receive messages.

### ISSUE THREAD

**Issue by babayotakun** [spring-projects/spring-integration#3604] opened 2021-07-29 14:06 UTC
This issues appeared somewhere between 5.4.6 (Spring Boot 2.4.5) and 5.5.2 (Spring Boot 2.5.3).

**Describe the bug**

If you have nested messaging gateway invocations (parent gateway's flow calls child gateway), then child gateway will hang on listening to temporary reply channel:
`  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:714)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1046)
	  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
	  at org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel.receive(GenericMessagingTemplate.java:314)`

**To Reproduce**

Create messaging gateway with replay channel. Connect it to the flow with transformer. In that transformer invoke another messaging gateway with replay channel. Whole flow will hang in that transformer.

**Expected behavior**

Child's messaging gateway successfully returns result from its reply channel.

**Sample**
Here sample project which demonstrates this issue: 
https://github.com/babayotakun/integration-bug

It will print "Test stop" on Spring Boot 2.4.5 and it will hang on 2.5.3.

**Comment by artembilan** [comment] 2021-07-29 15:44
Starting with Spring Boot `2.5`, Spring Integration does not create its own `TaskScheduler` any more. It really relies on whatever Spring Boot auto-configures for us: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.spring-integration.
It comes for us with a single thread for scheduling, which feels pretty sensible default.

To fix your problem and bring back an expected behavior, you need to add this into properties:
```
spring.task.scheduling.pool.size=10
```

Otherwise with only one thread and so many `QueueChannel`s in your application you stuck with a dead lock on that single scheduler's thread. Since gateways want their replies they wait indefinitely by default and therefore keeps a thread they are waiting in.
This way we got a dead lock for other processed to deal with that single scheduler's thread: they just can't produce anything since thread is busy already waiting on the other side.

Hope this clears things up a little bit.

See more info in docs about pollers and scheduling: https://docs.spring.io/spring-integration/docs/current/reference/html/configuration.html#namespace-taskscheduler

Closing with the provided workaround. Although I don't think we are going to change a consistent default behavior in Spring Boot. Unless you would insist that doc for Spring Integration over there has to be improved respectively...

**Closed by artembilan** 2021-07-29 15:44 UTC
Labels: status: waiting-for-triage, type: bug

**Comment by babayotakun** [comment] 2021-07-30 07:49
Thank you for your explanation!
`spring.task.scheduling.pool.size=10` worked in our case.
