### ISSUE TITLE
Aggregator is failing for multi node application

### ISSUE THREAD

**Issue by tusharjaggi1992** [spring-projects/spring-integration#3576] opened 2021-06-04 09:19 UTC
**In what version(s) of Spring Integration are you seeing this issue?**
5.2.1.RELEASE

**Describe the bug**
We have implemented Aggregator channel backed by a persistence message store in our application .
Which is running on a clustered environment with dual nodes.
The aggregator works fine and releases the message if poller from any one node fetches all the rows,
It fails to release if poller from both the nodes fetches few few rows

Consider an example - 
Release strategy - Message will be released when total rows will be 21
Poller from node 1 fetches 9 rows, processes them and inserts them into the INT_MESSAGE_GROUP table with corelation key
Poller from node 2 fetches the other remaining rows, processes them and tries to insert into the same INT_MESSAGE_GROUP table with same corelation key
ultimately results in Exception: ERROR: duplicate key value violates unique constraint "message_group_pk"
Hence the message is never released

Problematic Code Snippet
In class JdbcMessageStore.java --> addMessagesToGroup [Refer Code](https://github.com/spring-projects/spring-integration/blob/5.2.x/spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/store/JdbcMessageStore.java#L374) 

> try {
> 	doCreateMessageGroup(groupKey, createdDate);
> }
> catch (DuplicateKeyException e) {
> 	logger.warn("Lost race to create group; attempting update instead", e);
> 	doUpdateMessageGroup(groupKey, updatedDate);
> }

Actual Exception

> {\"level\":\"ERROR\",\"logger\":\"org.springframework.integration.handler.LoggingHandler\",\"msg\":\"org.springframework.messaging.MessageHandlingException: error occurred in message handler [bean 'org.springframework.integration.config.AggregatorFactoryBean#1' for component 'calllbackAggregator'; defined in: 'class path resource [SOMEFILE.xml]'; from source: ''int:aggregator' with id='calllbackAggregator'']; nested exception is org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [INSERT into INT_MESSAGE_GROUP(GROUP_KEY, REGION, MARKED, COMPLETE, LAST_RELEASED_SEQUENCE, CREATED_DATE, UPDATED_DATE) values (?, ?, 0, 0, 0, ?, ?)]; ERROR: duplicate key value violates unique constraint \\\"message_group_pk\\\"\\n  Detail: Key (group_key, region)=(a8f40833-2c89-311e-92a6-510b8c93bc53, DEFAULT) already exists.; nested exception is com.edb.util.PSQLException: ERROR: duplicate key value violates unique constraint \\\"message_group_pk\\\"\\n  Detail: Key (group_key, region)=(a8f40833-2c89-311e-92a6-510b8c93bc53, DEFAULT) already exists., failedMessage=GenericMessage [payload=SOME_PAYLOAD]\\n\\tat org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:191)\\n\\tat org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:187)\\n\\tat org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)\\n\\tat org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)\\n\\tat org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)\\n\\tat org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)\\n\\tat org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)\\n\\tat org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403)\\n\\tat org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)\\n\\tat org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)\\n\\tat org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)\\n\\tat org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)\\n\\tat org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:444)\\n\\tat org.springframework.integration.handler.AbstractMessageProducingHandler.doProduceOutput(AbstractMessageProducingHandler.java:318)\\n\\tat org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:266)\\n\\tat org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:229)\\n\\tat org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:133)\\n\\tat org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:170)\\n\\tat org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)\\n\\tat org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)\\n\\tat org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)\\n\\tat org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)\\n\\tat org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)\\n\\tat org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403)\\n\\tat org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)\\n\\tat org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)\\n\\tat org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)\\n\\tat org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)\\n\\tat org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:444)\\n\\tat org.springframework.integration.handler.AbstractMessageProducingHandler.doProduceOutput(AbstractMessageProducingHandler.java:318)\\n\\tat org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:266)\\n\\tat org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:229)\\n\\tat org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:133)\\n\\tat org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:170)\\n\\tat org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)\\n\\tat org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)\\n\\tat org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)\\n\\tat org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)\\n\\tat org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)\\n\\tat org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403)\\n\\tat org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)\\n\\tat org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)\\n\\tat org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)\\n\\tat org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)\\n\\tat org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutput(AbstractMessageProducingHandler.java:444)\\n\\tat org.springframework.integration.handler.AbstractMessageProducingHandler.doProduceOutput(AbstractMessageProducingHandler.java:318)\\n\\tat org.springframework.integration.handler.AbstractMessageProducingHandler.produceOutput(AbstractMessageProducingHandler.java:266)\\n\\tat org.springframework.integration.splitter.AbstractMessageSplitter.produceOutput(AbstractMessageSplitter.java:305)\\n\\tat org.springframework.integration.handler.AbstractMessageProducingHandler.sendOutputs(AbstractMessageProducingHandler.java:229)\\n\\tat org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:133)\\n\\tat org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:170)\\n\\tat org.springframework.integration.endpoint.PollingConsumer.handleMessage(PollingConsumer.java:143)\\n\\tat org.springframework.integration.endpoint.AbstractPollingEndpoint.messageReceived(AbstractPollingEndpoint.java:396)\\n\\tat org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:380)\\n\\tat sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)\\n\\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\\n\\tat java.lang.reflect.Method.invoke(Method.java:498)\\n\\tat org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)\\n\\tat org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)\\n\\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\\n\\tat org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)\\n\\tat org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)\\n\\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\\n\\tat org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)\\n\\tat com.sun.proxy.$Proxy369.call(Unknown Source)\\n\\tat org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:328)\\n\\tat org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$null$1(AbstractPollingEndpoint.java:275)\\n\\tat org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)\\n\\tat org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)\\n\\tat org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)\\n\\tat org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$2(AbstractPollingEndpoint.java:272)\\n\\tat org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)\\n\\tat org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)\\n\\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\\n\\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\\n\\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)\\n\\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)\\n\\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n\\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n\\tat java.lang.Thread.run(Thread.java:748)\\nCaused by: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [INSERT into INT_MESSAGE_GROUP(GROUP_KEY, REGION, MARKED, COMPLETE, LAST_RELEASED_SEQUENCE, CREATED_DATE, UPDATED_DATE) values (?, ?, 0, 0, 0, ?, ?)]; ERROR: duplicate key value violates unique constraint \\\"message_group_pk\\\"\\n  Detail: Key (group_key, region)=(a8f40833-2c89-311e-92a6-510b8c93bc53, DEFAULT) already exists.; nested exception is com.edb.util.PSQLException: ERROR: duplicate key value violates unique constraint \\\"message_group_pk\\\"\\n  Detail: Key (group_key, region)=(a8f40833-2c89-311e-92a6-510b8c93bc53, DEFAULT) already exists.\\n\\tat org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)\\n\\tat org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)\\n\\tat org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)\\n\\tat org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)\\n\\tat org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)\\n\\tat org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)\\n\\tat org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:862)\\n\\tat org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:917)\\n\\tat org.springframework.integration.jdbc.store.JdbcMessageStore.doCreateMessageGroup(JdbcMessageStore.java:636)\\n\\tat org.springframework.integration.jdbc.store.JdbcMessageStore.addMessagesToGroup(JdbcMessageStore.java:372)\\n\\tat org.springframework.integration.store.AbstractMessageGroupStore.addMessageToGroup(AbstractMessageGroupStore.java:190)\\n\\tat org.springframework.integration.aggregator.AbstractCorrelatingMessageHandler.store(AbstractCorrelatingMessageHandler.java:775)\\n\\tat org.springframework.integration.aggregator.AbstractCorrelatingMessageHandler.processMessageForGroup(AbstractCorrelatingMessageHandler.java:492)\\n\\tat org.springframework.integration.aggregator.AbstractCorrelatingMessageHandler.handleMessageInternal(AbstractCorrelatingMessageHandler.java:471)\\n\\tat org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:170)\\n\\t... 78 more\\nCaused by: com.edb.util.PSQLException: ERROR: duplicate key value violates unique constraint \\\"message_group_pk\\\"\\n  Detail: Key (group_key, region)=(a8f40833-2c89-311e-92a6-510b8c93bc53, DEFAULT) already exists.\\n\\tat com.edb.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2679)\\n\\tat com.edb.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2266)\\n\\tat com.edb.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:315)\\n\\tat com.edb.jdbc.PgStatement.executeInternal(PgStatement.java:476)\\n\\tat com.edb.jdbc.PgStatement.execute(PgStatement.java:397)\\n\\tat com.edb.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:193)\\n\\tat com.edb.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:161)\\n\\tat sun.reflect.GeneratedMethodAccessor236.invoke(Unknown Source)\\n\\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\\n\\tat java.lang.reflect.Method.invoke(Method.java:498)\\n\\tat org.apache.tomcat.jdbc.pool.interceptor.StatementDecoratorInterceptor$StatementProxy.invoke(StatementDecoratorInterceptor.java:237)\\n\\tat com.sun.proxy.$Proxy313.executeUpdate(Unknown Source)\\n\\tat sun.reflect.GeneratedMethodAccessor236.invoke(Unknown Source)\\n\\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\\n\\tat java.lang.reflect.Method.invoke(Method.java:498)\\n\\tat org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)\\n\\tat com.sun.proxy.$Proxy313.executeUpdate(Unknown Source)\\n\\tat org.springframework.jdbc.core.JdbcTemplate.lambda$update$0(JdbcTemplate.java:867)\\n\\tat org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)\\n\\t... 87 more\\n\"  }

**To Reproduce**
Create an aggregator and define release strategy for total of 21 rows
Mannually insert a record in int_message_group with UUID of corelation key as group id
When poller will pick and try to insert It will give exception as DataIntegrityViolationException which is not handled
And It will get stuck and never get released

**Expected behavior**
DataIntegrityViolationException should also be handled and in case of duplicate key update should be done

**Comment by artembilan** [comment] 2021-06-04 16:49
Why don't you say what database causes the problem?
It really doesn't fail for us with H2, HSQL and Derby since all of them throw a `DuplicateKeyException`.

Can you also, please, format a stack trace the way it can be read clearly?
Right now it is a mess of a single line with those line separators concatenating to sentences...

We had similar discussion on Gitter: https://gitter.im/spring-projects/spring-integration?at=60b7350fa10461235db22644, but doesn't look like you add more info to the story.
It is also not clear yet if the problem is really on Spring Integration side. Maybe you should configure your database somehow to throw the proper error code for mapping it to that `DuplicateKeyException` in the end?..

**Comment by artembilan** [comment] 2021-06-21 17:38
It probably also would be great to see some DEBUG logs for `org.springframework.jdbc.support` category. Just to understand what error codes are mapped to your database.
If we assume that we talk about PostgreSQL, then we have a config like this:
```
	<property name="duplicateKeyCodes">
			<value>21000,23505</value>
	</property>
	<property name="dataIntegrityViolationCodes">
			<value>23000,23502,23503,23514</value>
	</property>
```

Or your database doesn't return that code properly, or Spring has to be improved to respective error code or even fully to your vendor.
Not Spring Integration matter though...

Thanks for understanding

(Will close it next week as `Invalid` if no any feedback)

**Closed** 2021-07-01 06:18 UTC
Labels: in: jdbc, status: waiting-for-reporter, type: bug

**Comment by tusharjaggi1992** [comment] 2021-07-01 06:20
Found the issue , the database product name was coming as EnterpriseDB instead of PostgresSQL.
Closing the issue
