### ISSUE TITLE
org.springframework.integration:spring-integration-jdbc. Distributed lock allows 2nd process to acquire lock on lockKey inspite of being locked by 1st process

### ISSUE THREAD

**Issue by sharadlonkar** [spring-projects/spring-integration#3724] opened 2022-02-10 17:41 UTC
Current implementation allows 2nd process to acquire lock on lockKey inspite of 1st Process holding lock for lockKey.

int_lock data structure

lock_key | region | client_id | created_date
acct1 | default | dockerAPI | 2021-02-10 05:00:00

Scenario

Given
      Thread 1 of client:dockerAPI has acquired lock for lockKey:acct1  
      AND Thread 1 processing is in progress 
      AND Thread 1 is holding lock on lockKey:acct1  for client:dockerAPI
WHEN      
      Thread 2 tries to acquire lock using client:dockerAPI for lockKey:acct1 
THEN 
      Thread 2 should be not be able to acquire lock using client:dockerAPI for lockKey:acct1  
   
CURRENT API implementation : Thread 2 is able to acquire lock on using client:dockerAPI for lockKey:acct1 inspite of Thread 1 holding lock on lockKey:acct1 and updates the Created_time on lockKey record
   
Please refer logic for lock acquire here - https://github.com/spring-projects/spring-integration/blob/main/spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/DefaultLockRepository.java#L167

**Comment by artembilan** [comment] 2022-02-11 18:29
Sorry, your last comment is not fully clear, even if I wrapped some code. 
Looks copy/paste addition to your previous one.

Let's see if we are on the same page!

1. Different processed has to have different client id. That's the rule and that's how we keep the lock distributed. Same client id will lead to unexpected behavior.
2. We cannot remove that piece of logic with an UPDATE since exactly this one belongs to the particular re-enter lock functionality. Or when the lock is too old to be held in the DB yet.
See this `UPDATE %sLOCK SET CLIENT_ID=?, CREATED_DATE=? WHERE REGION=? AND LOCK_KEY=? AND (CLIENT_ID=? OR CREATED_DATE<?)`. So, it can pass only if there is data and it has the same client or data has been expired.
If it is `false`, we go to `INSERT`.
3. The `INSERT INTO %sLOCK (REGION, LOCK_KEY, CLIENT_ID, CREATED_DATE) VALUES (?, ?, ?, ?)` cannot pass for different client because there is (or it must be) a constraint on the table:
```
constraint INT_LOCK_PK primary key (LOCK_KEY, REGION)
```

What do I miss, please?

**Comment by artembilan** [comment] 2022-02-15 18:14
Any updates, please?

I still find your PR as invalid and don't see any problems you describe with the proper DB configuration.

The issue will be closed as `Invalid` next week if no answer...

**Comment by artembilan** [comment] 2022-02-28 20:07
Closed as `Invalid` with conclusions made above.

**Closed by artembilan** 2022-02-28 20:07 UTC
Labels: status: waiting-for-reporter
