### ISSUE TITLE
Application Fails to Start with spring-integration-core Version 6.3.6

### ISSUE THREAD

**Issue by hkathi-loyaltymethods** [spring-projects/spring-integration#9693] opened 2024-12-02 09:04 UTC
I have added the following dependency to my Spring Boot application. When using version 6.3.2, the service works fine. However, to address the ConcurrentModificationException issue that was fixed in version 6.3.6, I need to include this dependency under the **dependencyManagement** section.
https://github.com/spring-projects/spring-integration/releases/tag/v6.3.6

```
			<dependency>
				<groupId>org.springframework.integration</groupId>
				<artifactId>spring-integration-core</artifactId>
				<version>6.3.6</version>
				<scope>compile</scope>
			</dependency>
```

**Application startup failure logs**
```
proxy_1  | org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'meterRegistryCloser': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
proxy_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.event.AbstractApplicationEventMulticaster.retrieveApplicationListeners(AbstractApplicationEventMulticaster.java:265) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.event.AbstractApplicationEventMulticaster.getApplicationListeners(AbstractApplicationEventMulticaster.java:222) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:457) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1130) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1093) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:114) ~[spring-cloud-context-4.1.3.jar!/:4.1.3]
proxy_1  | 	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:211) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1202) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1195) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1186) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:637) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.0.jar!/:3.3.0]
proxy_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.0.jar!/:3.3.0]
proxy_1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.0.jar!/:3.3.0]
proxy_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.0.jar!/:3.3.0]
proxy_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.0.jar!/:3.3.0]
proxy_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.0.jar!/:3.3.0]
proxy_1  | 	at com.rcx.sei.proxy.RcxProxyApplication.main(RcxProxyApplication.java:32) ~[!/:3.5.0]
proxy_1  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
proxy_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
proxy_1  | 	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[rcx-sei-proxy-3.5.0.jar:3.5.0]
proxy_1  | 	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[rcx-sei-proxy-3.5.0.jar:3.5.0]
proxy_1  | 	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[rcx-sei-proxy-3.5.0.jar:3.5.0]
proxy_1  | [WARN ] 2024-12-02 08:53:25.872 [rcx-sei-proxy,] org.springframework.context.annotation.AnnotationConfigApplicationContext - Exception thrown from ApplicationListener handling ContextClosedEvent
proxy_1  | org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'meterRegistryCloser': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
proxy_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:220) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.event.AbstractApplicationEventMulticaster.retrieveApplicationListeners(AbstractApplicationEventMulticaster.java:265) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.event.AbstractApplicationEventMulticaster.getApplicationListeners(AbstractApplicationEventMulticaster.java:222) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:457) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1130) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1093) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:114) ~[spring-cloud-context-4.1.3.jar!/:4.1.3]
proxy_1  | 	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:211) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1202) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1195) ~[spring-beans-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1186) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:637) ~[spring-context-6.1.8.jar!/:6.1.8]
proxy_1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.0.jar!/:3.3.0]
proxy_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.0.jar!/:3.3.0]
proxy_1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.0.jar!/:3.3.0]
proxy_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.0.jar!/:3.3.0]
proxy_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.0.jar!/:3.3.0]
proxy_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.0.jar!/:3.3.0]
proxy_1  | 	at com.rcx.sei.proxy.RcxProxyApplication.main(RcxProxyApplication.java:32) ~[!/:3.5.0]
proxy_1  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
proxy_1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
proxy_1  | 	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[rcx-sei-proxy-3.5.0.jar:3.5.0]
proxy_1  | 	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[rcx-sei-proxy-3.5.0.jar:3.5.0]
proxy_1  | 	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[rcx-sei-proxy-3.5.0.jar:3.5.0]
proxy_1  | [ERROR] 2024-12-02 08:53:26.196 [rcx-sei-proxy,] org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - 
proxy_1  | 
proxy_1  | ***************************
proxy_1  | APPLICATION FAILED TO START
proxy_1  | ***************************
proxy_1  | 
proxy_1  | Description:
proxy_1  | 
proxy_1  | An attempt was made to call a method that does not exist. The attempt was made from the following location:
proxy_1  | 
proxy_1  |     org.springframework.integration.config.IntegrationSimpleEvaluationContextFactoryBean.getObject(IntegrationSimpleEvaluationContextFactoryBean.java:85)
proxy_1  | 
proxy_1  | The following method did not exist:
proxy_1  | 
proxy_1  |     'org.springframework.expression.spel.support.SimpleEvaluationContext$Builder org.springframework.expression.spel.support.SimpleEvaluationContext$Builder.withAssignmentDisabled()'
proxy_1  | 
proxy_1  | The calling method's class, org.springframework.integration.config.IntegrationSimpleEvaluationContextFactoryBean, was loaded from the following location:
proxy_1  | 
proxy_1  |     jar:nested:/home/rcx/rcx-sei-proxy/target/rcx-sei-proxy-3.5.0.jar/!BOOT-INF/lib/spring-integration-core-6.2.8.jar!/org/springframework/integration/config/IntegrationSimpleEvaluationContextFactoryBean.class
proxy_1  | 
proxy_1  | The called method's class, org.springframework.expression.spel.support.SimpleEvaluationContext$Builder, is available from the following locations:
proxy_1  | 
proxy_1  |     jar:nested:/home/rcx/rcx-sei-proxy/target/rcx-sei-proxy-3.5.0.jar/!BOOT-INF/lib/spring-expression-6.1.8.jar!/org/springframework/expression/spel/support/SimpleEvaluationContext$Builder.class
proxy_1  | 
proxy_1  | The called method's class hierarchy was loaded from the following locations:
proxy_1  | 
proxy_1  |     org.springframework.expression.spel.support.SimpleEvaluationContext.Builder: jar:nested:/home/rcx/rcx-sei-proxy/target/rcx-sei-proxy-3.5.0.jar/!BOOT-INF/lib/spring-expression-6.1.8.jar!/
proxy_1  | 
proxy_1  | 
proxy_1  | Action:
proxy_1  | 
proxy_1  | Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.integration.config.IntegrationSimpleEvaluationContextFactoryBean and org.springframework.expression.spel.support.SimpleEvaluationContext$Builder
proxy_1  | 
proxy_1 exited with code 1
```

Can someone please look into it and let me know if any more information required from me.

**Comment by artembilan** [comment] 2024-12-02 20:41
Such a modification to dependencies is not correct.
You still use Spring Boot `3.3.0` and Spring Framework `6.1.8` trying to upgrade only `spring-integration-core`.
Which is also not correct, since better to upgrade the whole BOM.
See more info how to change versions in Spring Boot projects: https://docs.spring.io/spring-boot/maven-plugin/using.html#using.parent-pom.

However it looks more like better to upgrade the whole Spring Boot to a newer version and that's it: https://spring.io/projects/spring-boot#learn.
I mean `3.3.6` is there for you which already includes Spring Integration `6.3.6`.

Closed as `Works as Designed`.

**Closed by artembilan** 2024-12-02 20:41 UTC
Labels: type: bug, status: waiting-for-triage
