### ISSUE TITLE
Spring startup failure when WebApplicationType is set to "reactive"

### ISSUE THREAD

**Issue by Numbernick** [spring-projects/spring-integration#2933] opened 2019-05-15 10:27 UTC
**Affects Version(s):**
* Spring stream reactive: 2.1.0
* Spring Cloud GCP PubSub Stream Binder: 1.1.0

## Bug report
When using SpringStreamBinder and Webflux, everything is basically fine. When I change the WebApplicationType to "reactive" via properties (```spring.main.web-application-type=reactive```), the whole application breaks with an Exception at startup. For my useCase I have to add the property because Spring WebMvc also is on the classpath (e.g. because of Hateoas) and I have to tell Spring to load the reactive server. The whole stacktrace is as follows:
```
java.lang.IllegalStateException: Failed to load ApplicationContext

	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:44)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ReactiveWebApplicationContext due to missing ReactiveWebServerFactory bean.
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:127)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 25 more
Caused by: org.springframework.context.ApplicationContextException: Unable to start reactive web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ReactiveWebApplicationContext due to missing ReactiveWebServerFactory bean.
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:82)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:67)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:250)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:174)
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:120)
	at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:313)
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:94)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindInputs(BindableProxyFactory.java:234)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:54)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:47)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:33)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	... 37 more
Caused by: org.springframework.context.ApplicationContextException: Unable to start ReactiveWebApplicationContext due to missing ReactiveWebServerFactory bean.
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.getWebServerFactory(ReactiveWebServerApplicationContext.java:106)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.createWebServer(ReactiveWebServerApplicationContext.java:90)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.onRefresh(ReactiveWebServerApplicationContext.java:79)
	... 54 more
```
I also added a small sample application with a test case showing the error. You just have to add your own Google Cloud Credentials to let it run. (I haven't tested if the error occures with other stream binder implementations as well, even though this might be the case. The Exception doesn't seem to be a GoogleCloud specific error).

I don't know how this could happen, but I don't expect the normal configuration for switching the server-stack to break the whole application. Also I don't know why the application is starting the reactive server properly without the property in place. I would expect this to lead to the same error as with the WebApplicationType set manually since the aplicationType IS reactive even without setting the property.

For now I'll remove the SpringIntegration-Part from my project since I don't need it right now (lucky me). I don't know of any workarround so far.

[springReactiveTest.zip](https://github.com/spring-projects/spring-integration/files/3182054/springReactiveTest.zip)

**Comment by artembilan** [comment] 2019-05-15 13:35
It doesn't sound like an issue related to https://spring.io/projects/spring-integration[Spring Integration].

According to your stack trace there is really nothing about Spring Integration.
It sounds like you don't have enough dependencies in your classpath:
```
Caused by: org.springframework.context.ApplicationContextException: Unable to start ReactiveWebApplicationContext due to missing ReactiveWebServerFactory bean.
```

Such a bean is created in this configuration: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/ReactiveWebServerFactoryAutoConfiguration.java

Are you sure that you have one of those dependencies for the proper auto-configuration?

I'll take a look into your project lately, but surely this doesn't belong to Spring Integration...

Any insights made you think the problem is exactly with Spring Integration?

Thanks

**Comment by Numbernick** [comment] 2019-05-15 14:06
@artembilan Thank you for your response. According to the example project this behaviour only occures when I enable the StreamBinding. I marked the line in the code in the ```ApplicationContext```: ```@EnableBinding(Channels.class)```. There are two facts leading me to spring integration:
* Without spring integration the project starts up perfectly fine. Even when webmvc and webflux are configured and the property ```spring.main.web-application-type``` is set to ```reactive```. This can also be verified by just commenting out the ```@EnableBinging```-Annotation on the ApplicationContext which lets the Application start up as well.
* With spring integration and removing the property ```spring.main.web-application-type```, the application starts normally. (Which is strange, since the server still is reactive and setting the property manually or letting springe decide which server to start should lead to the same outcome --> running reactive application.)

So everything is working fine. **Except** when the property has to be set (e.g. because webflux and webmcv are in the project and i want to start the reactive server).

**Comment by artembilan** [comment] 2019-05-15 14:23
FYI: the `@EnableBinding` is a part of Spring Cloud Stream project: https://spring.io/projects/spring-cloud-stream

**Comment by Numbernick** [comment] 2019-05-15 14:32
Oh, my misstake. I thought Spring Integration and Spring Cloud Stream would work together as one. So if this is the wrong place, is it possible to move this issue to Spring Cloud Stream then? Otherwise I'll create a new issue over there.

**Comment by artembilan** [comment] 2019-05-15 14:40
I'm not sure what is going on yet, but to clarify things a little bit: the binder in Spring Cloud Stream is started in its own `ApplicationContext`. We can see that in that stack trace:
```
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:250) ~[spring-cloud-stream-2.1.0.RELEASE.jar:2.1.0.RELEASE]
```

In most cases the parent configuration properties are propagated to that child application context. Not sure though why it doesn't see that `ReactiveWebServerFactory` over there...

Well, unfortunately we can't move GH issues in between org. So, only the way is to close this one and open an new one over there with the link here.

We continue discussion and investigation in that project then.

Thanks for understanding

**Comment by artembilan** [comment] 2019-05-15 14:54
So, yes. That's the culprit!

We definitely need to move this issue into Spring Cloud Stream and consider what we can do that with that `DefaultBinderFactory.getBinderInstance()` to explicitly override that `spring.main.web-application-type` with desired `NONE`.

**Comment by artembilan** [comment] 2019-05-15 14:55
Closed as `Invalid` in terms of Spring Integration, but must be reopened in Spring Cloud Stream.

Thanks

**Closed by artembilan** 2019-05-15 14:55 UTC
Labels: Invalid

**Comment by Numbernick** [comment] 2019-05-15 15:14
@artembilan Thank you very much for the clarification. Seems like someone else has this issue as well :)
