### ISSUE TITLE
need to disable "attempting to receive mail from folder" log

### ISSUE THREAD

**Issue by MarsDown** [spring-projects/spring-integration#3430] opened 2020-11-15 15:32 UTC
i need to disable "attempting to receive mail from folder " log in spring integration.

Because it writes a lot of logs in catalina.out Tomcat and increases the file size.

I do not want to use the delay in poling .

sample:

2020-11-15 18:45:51.050  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:51.198  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:51.321  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:51.437  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:51.552  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:52.423  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:52.545  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:52.669  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:52.800  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:53.001  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:53.131  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:53.252  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:53.372  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:53.503  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:53.631  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:53.752  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:53.881  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:53.993  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:54.118  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:54.579  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:54.700  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:54.850  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:54.970  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:55.104  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:55.220  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:55.351  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:55.572  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:55.690  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:55.820  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]
2020-11-15 18:45:55.940  INFO 3476 --- [ask-scheduler-5] o.s.i.m.ImapMailReceiver                 : attempting to receive mail from folder [INBOX]

**Comment by artembilan** [comment] 2020-11-16 14:27
Looks like this is your SO question with the same matter: https://stackoverflow.com/questions/64846191/how-disable-attempting-to-receive-mail-from-folder-spring-integration-mail-in.

This is not a bug, but just an improvement request.

It is already a `DEBUG` message starting with version `5.4`: https://github.com/spring-projects/spring-integration/commit/9ad348b75f91630c0c197068033eceb4e97d8f75#diff-de4001fbf6502d7d9069aee66e68de592c340d1a7814f34260acb9c794b37538.

So, closing respectively.

**Closed by artembilan** 2020-11-16 14:27 UTC
Labels: status: waiting-for-triage, type: bug

**Comment by artembilan** [comment] 2020-11-16 14:28
The PR from the past: https://github.com/spring-projects/spring-integration/pull/3312
