### ISSUE TITLE
ClassCastException in AbstractPollingEndpoint

### ISSUE THREAD

**Issue by toddlindner** [spring-projects/spring-integration#3418] opened 2020-10-30 14:00 UTC
Spring Integration 5.3.2.RELEASE

I am seeing a `ClassCastException` during error handling in `AbstractPollingEndpoint`.  Using jdk15 so there is more detail on the `ClassCastException`.

The thing is, looking at this line
https://github.com/spring-projects/spring-integration/blob/fb35a736d6fc159f9bd34794ff9fdb97b05462d9/spring-integration-core/src/main/java/org/springframework/integration/endpoint/AbstractPollingEndpoint.java#L417

For the life of me, I can't understand how a non `RuntimeException` can make it here.  In my case I am getting `java.nio.file.NoSuchFileException`.  Understand this is not an ideal bug report, but as a pure Java dev, I still cant figure out how a non-runtime exception can make it to line 417.  The `receiveMessage()` method above has no throws declared so the exception thrown must be a `RuntimeException`, but `java.nio.file.NoSuchFileException` is not.  The only thing I can think of would be some sort of lombok `@SneakyThrows` somewhere but that would still create a `UndeclaredThrowableException` around the inner exception.

I am not trying to stop the exception (I assume a user had a file locked during polling or something similar), I just want to get a normal throw without a `ClassCastException`.

This error only happens about once per day so it is difficult to reproduce.  The app has about 10 pollers but they are all similar.  Unfortunately I don't know which one is failing since there is no other information in the log or the stack trace regarding bean id. 

The spring configuraiton xml is using this adapter `<int-file:inbound-channel-adapter>`

```
2020-10-29 22:19:09,833 [scheduling-1] ERROR    o.s.i.handler.LoggingHandler - org.springframework.messaging.MessagingException: nested exception is java.lang.ClassCastException: class java.nio.file.NoSuchFileException cannot be cast to class java.lang.RuntimeException (java.nio.file.NoSuchFileException and java.lang.RuntimeException are in module java.base of loader 'bootstrap')
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:390)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$null$3(AbstractPollingEndpoint.java:323)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$4(AbstractPollingEndpoint.java:320)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ClassCastException: class java.nio.file.NoSuchFileException cannot be cast to class java.lang.RuntimeException (java.nio.file.NoSuchFileException and java.lang.RuntimeException are in module java.base of loader 'bootstrap')
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:417)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:376)
	... 13 more
```

**Comment by artembilan** [comment] 2020-10-30 18:20
> Right but `receiveMessage()` can only throw RTEs.

Correct. That's why I suggest to use a `ReflectionUtils.rethrowRuntimeException()`. See it's impl.

We probably have just never seen this problem because we are mostly on Java 8 yet.

**Comment by garyrussell** [comment] 2020-10-30 18:27
I reproduced it quite easily; I don't see any such code in the framework.

@toddlindner - if you want to track down the root cause (where the actual exception is thrown), you can add this advice to the poller:

```java
private ReceiveMessageAdvice errorTrapper() {
	return new ReceiveMessageAdvice() {

		@Override
		@Nullable
		public Object invoke(MethodInvocation invocation) throws Throwable {
			try {
				return ReceiveMessageAdvice.super.invoke(invocation);
			}
			catch (RuntimeException e) {
				throw e;
			}
			catch (Exception e) {
				throw new IllegalStateException(e);
			}
		}

		@Override
		@Nullable
		public Message<?> afterReceive(@Nullable Message<?> result, Object source) {
			return null;
		}

	};
}
```

This assumes SI 5.3 or later, for earlier versions (4.2 or later) you would have to extend `AbstractMessageSourceAdvice`.

Here's the complete test app:

```java
@SpringBootApplication
public class Sigh3418Application {


	private static final Logger LOG = LoggerFactory.getLogger(Sigh3418Application.class);


	public static void main(String[] args) {
		SpringApplication.run(Sigh3418Application.class, args);
	}

	@Bean
	public IntegrationFlow flow() {
		return IntegrationFlows.from(new MyMS(), e -> e.poller(Pollers.fixedDelay(5000).advice(errorTrapper())))
				.nullChannel();
 	}

	private ReceiveMessageAdvice errorTrapper() {
		return new ReceiveMessageAdvice() {

			@Override
			@Nullable
			public Object invoke(MethodInvocation invocation) throws Throwable {
				try {
					return ReceiveMessageAdvice.super.invoke(invocation);
				}
				catch (RuntimeException e) {
					throw e;
				}
 				catch (Exception e) {
					throw new IllegalStateException(e);
				}
			}

			@Override
			@Nullable
			public Message<?> afterReceive(@Nullable Message<?> result, Object source) {
				return null;
			}

		};
	}

}

class MyMS implements MessageSource<String> {

	@Override
	@Nullable
	public Message<String> receive() {
		try {
			Foo.class.newInstance();
		}
		catch (InstantiationException | IllegalAccessException e) {
		}
		return null;
	}

}

class Foo {

	public Foo() throws IOException {
		throw new IOException();
	}

}
```

**Comment by garyrussell** [comment] 2020-10-30 18:31
>We probably have just never seen this problem because we are mostly on Java 8 yet.

?? It fails with Java8 the same way.

**Comment by toddlindner** [comment] 2020-10-30 18:32
Thanks guys.  Wow good catch Juergen and Gary on the Class.newInstance() issue.  I never would have thought that was possible.
Agree ReflectionUtils.rethrowRuntimeException() seems like the cleanest fix here.

**Comment by artembilan** [comment] 2020-10-30 18:35
So, @garyrussell , I assign this to you because it looks like you are fully on board with the problem.

Thanks

**Closed** 2020-11-02 16:37 UTC
Labels: backport 4.3.x, backport 5.2.x, backport 5.3.x, status: waiting-for-triage, type: bug

**Comment by toddlindner** [comment] 2021-01-25 14:41
Now that I am running the release I found the root cause of this.  I had been using lombok @SneakyThrows on the accept() method of a FileListFilter, and it was throwing java.lang.reflect.UndeclaredThrowableException
